// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Table("AppliedOffersLog")]
[Index("OfferId", Name = "ix_AppliedOffersLog_OfferId")]
[Index("SaleId", Name = "ix_AppliedOffersLog_SaleId")]
public partial class AppliedOffersLog
{
    [Key]
    public int AppliedOfferLogId { get; set; }

    public int SaleId { get; set; }

    public int? SaleItemId { get; set; }

    public int? OfferId { get; set; }

    [StringLength(255)]
    public string OfferCode { get; set; }

    [StringLength(255)]
    public string OfferName { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal DiscountAmount { get; set; }

    public DateTime AppliedOn { get; set; }

    public int? AppliedBy { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("AppliedBy")]
    [InverseProperty("AppliedOffersLogs")]
    public virtual User AppliedByNavigation { get; set; }

    [ForeignKey("OfferId")]
    [InverseProperty("AppliedOffersLogs")]
    public virtual Offer Offer { get; set; }

    [ForeignKey("SaleId")]
    [InverseProperty("AppliedOffersLogs")]
    public virtual SalesHeader Sale { get; set; }

    [ForeignKey("SaleItemId")]
    [InverseProperty("AppliedOffersLogs")]
    public virtual SalesItem SaleItem { get; set; }
}