// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("BranchId", Name = "ix_AppSettings_BranchId")]
public partial class AppSetting
{
    [Key]
    public int SettingId { get; set; }

    [Required]
    [StringLength(255)]
    public string SettingKey { get; set; }

    public string SettingValue { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    public int? BranchId { get; set; }

    public bool IsActive { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int? UpdatedBy { get; set; }

    public int? CreatedBy { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("AppSettings")]
    public virtual Branch Branch { get; set; }

    [ForeignKey("UpdatedBy")]
    [InverseProperty("AppSettings")]
    public virtual User UpdatedByNavigation { get; set; }
}