// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("PerformedBy", Name = "ix_AuditLogs_PerformedBy")]
[Index("PerformedOn", Name = "ix_AuditLogs_PerformedOn")]
public partial class AuditLog
{
    [Key]
    public int AuditLogId { get; set; }

    [StringLength(255)]
    public string ModuleName { get; set; }

    [StringLength(100)]
    public string ActionType { get; set; }

    [StringLength(255)]
    public string ReferenceType { get; set; }

    public int? ReferenceId { get; set; }

    public string OldDataJson { get; set; }

    public string NewDataJson { get; set; }

    public DateTime PerformedOn { get; set; }

    public int? PerformedBy { get; set; }

    [StringLength(255)]
    public string IpAddress { get; set; }

    [StringLength(255)]
    public string DeviceInfo { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("PerformedBy")]
    [InverseProperty("AuditLogs")]
    public virtual User PerformedByNavigation { get; set; }
}