// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("BranchId", Name = "ix_BarcodePrintBatches_BranchId")]
public partial class BarcodePrintBatch
{
    [Key]
    public int BarcodePrintBatchId { get; set; }

    public int BranchId { get; set; }

    [StringLength(255)]
    public string BatchNo { get; set; }

    public DateTime? PrintDate { get; set; }

    public int? PrintedBy { get; set; }

    [StringLength(255)]
    public string PrinterName { get; set; }

    public int? TotalLabels { get; set; }

    [StringLength(255)]
    public string Remarks { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [InverseProperty("BarcodePrintBatch")]
    public virtual ICollection<BarcodePrintBatchItem> BarcodePrintBatchItems { get; set; } = new List<BarcodePrintBatchItem>();

    [ForeignKey("BranchId")]
    [InverseProperty("BarcodePrintBatches")]
    public virtual Branch Branch { get; set; }

    [ForeignKey("PrintedBy")]
    [InverseProperty("BarcodePrintBatches")]
    public virtual User PrintedByNavigation { get; set; }
}