// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("BarcodePrintBatchId", Name = "ix_BarcodePrintBatchItems_BatchId")]
[Index("ItemVariantId", Name = "ix_BarcodePrintBatchItems_ItemVariantId")]
public partial class BarcodePrintBatchItem
{
    [Key]
    public int BarcodePrintBatchItemId { get; set; }

    public int BarcodePrintBatchId { get; set; }

    public int ItemId { get; set; }

    public int? ItemVariantId { get; set; }

    [StringLength(255)]
    public string BarcodeValue { get; set; }

    [StringLength(255)]
    public string ColourName { get; set; }

    [StringLength(255)]
    public string SizeName { get; set; }

    [StringLength(255)]
    public string StyleNo { get; set; }

    public int LabelCount { get; set; }

    [StringLength(50)]
    public string PrintedStatus { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("BarcodePrintBatchId")]
    [InverseProperty("BarcodePrintBatchItems")]
    public virtual BarcodePrintBatch BarcodePrintBatch { get; set; }

    [ForeignKey("ItemId")]
    [InverseProperty("BarcodePrintBatchItems")]
    public virtual Item Item { get; set; }

    [ForeignKey("ItemVariantId")]
    [InverseProperty("BarcodePrintBatchItems")]
    public virtual ItemVariant ItemVariant { get; set; }
}