// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("BrandCode", Name = "uq_Brands_BrandCode", IsUnique = true)]
public partial class Brand
{
    [Key]
    public int BrandId { get; set; }

    [StringLength(255)]
    public string BrandCode { get; set; }

    [StringLength(255)]
    public string BrandName { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal DiscountPct { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [InverseProperty("Brand")]
    public virtual ICollection<Item> Items { get; set; } = new List<Item>();

    [InverseProperty("Brand")]
    public virtual ICollection<OfferItem> OfferItems { get; set; } = new List<OfferItem>();
}