// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("CompanyId", Name = "ix_Branches_CompanyId")]
[Index("CompanyId", "BranchCode", Name = "uq_Branches_CompanyBranchCode", IsUnique = true)]
public partial class Branch
{
    [Key]
    public int BranchId { get; set; }

    public int CompanyId { get; set; }

    [StringLength(255)]
    public string BranchCode { get; set; }

    [StringLength(255)]
    public string BranchName { get; set; }

    [StringLength(255)]
    public string Gstin { get; set; }

    [StringLength(255)]
    public string Address1 { get; set; }

    [StringLength(255)]
    public string Address2 { get; set; }

    [StringLength(255)]
    public string Address3 { get; set; }

    [StringLength(255)]
    public string City { get; set; }

    [StringLength(255)]
    public string State { get; set; }

    [StringLength(255)]
    public string Country { get; set; }

    [StringLength(255)]
    public string Pincode { get; set; }

    [StringLength(255)]
    public string Phone { get; set; }

    [StringLength(255)]
    public string Email { get; set; }

    public bool IsMainBranch { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [InverseProperty("Branch")]
    public virtual ICollection<AppSetting> AppSettings { get; set; } = new List<AppSetting>();

    [InverseProperty("Branch")]
    public virtual ICollection<BarcodePrintBatch> BarcodePrintBatches { get; set; } = new List<BarcodePrintBatch>();

    [InverseProperty("Branch")]
    public virtual ICollection<CashierShift> CashierShifts { get; set; } = new List<CashierShift>();

    [ForeignKey("CompanyId")]
    [InverseProperty("Branches")]
    public virtual Company Company { get; set; }

    [InverseProperty("Branch")]
    public virtual ICollection<CounterPayout> CounterPayouts { get; set; } = new List<CounterPayout>();

    [InverseProperty("Branch")]
    public virtual ICollection<Counter> Counters { get; set; } = new List<Counter>();

    [InverseProperty("Branch")]
    public virtual ICollection<DailySalesSummary> DailySalesSummaries { get; set; } = new List<DailySalesSummary>();

    [InverseProperty("Branch")]
    public virtual ICollection<Device> Devices { get; set; } = new List<Device>();

    [InverseProperty("Branch")]
    public virtual ICollection<HeldBill> HeldBills { get; set; } = new List<HeldBill>();

    [InverseProperty("Branch")]
    public virtual ICollection<Item> Items { get; set; } = new List<Item>();

    [InverseProperty("Branch")]
    public virtual ICollection<PurchaseHeader> PurchaseHeaders { get; set; } = new List<PurchaseHeader>();

    [InverseProperty("Branch")]
    public virtual ICollection<PurchaseReturn> PurchaseReturns { get; set; } = new List<PurchaseReturn>();

    [InverseProperty("Branch")]
    public virtual ICollection<SalesHeader> SalesHeaders { get; set; } = new List<SalesHeader>();

    [InverseProperty("Branch")]
    public virtual ICollection<SalesReturn> SalesReturns { get; set; } = new List<SalesReturn>();

    [InverseProperty("Branch")]
    public virtual ICollection<SchemeMaster> SchemeMasters { get; set; } = new List<SchemeMaster>();

    [InverseProperty("Branch")]
    public virtual ICollection<StockAdjustment> StockAdjustments { get; set; } = new List<StockAdjustment>();

    [InverseProperty("Branch")]
    public virtual ICollection<StockLedger> StockLedgers { get; set; } = new List<StockLedger>();

    [InverseProperty("FromBranch")]
    public virtual ICollection<StockTransfer> StockTransferFromBranches { get; set; } = new List<StockTransfer>();

    [InverseProperty("ToBranch")]
    public virtual ICollection<StockTransfer> StockTransferToBranches { get; set; } = new List<StockTransfer>();

    [InverseProperty("Branch")]
    public virtual ICollection<User> Users { get; set; } = new List<User>();
}