// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("BranchId", Name = "ix_CashierShifts_BranchId")]
[Index("CounterId", Name = "ix_CashierShifts_CounterId")]
[Index("UserId", Name = "ix_CashierShifts_UserId")]
public partial class CashierShift
{
    [Key]
    public int ShiftId { get; set; }

    public int BranchId { get; set; }

    public int CounterId { get; set; }

    public int UserId { get; set; }

    public DateTime? OpeningTime { get; set; }

    public DateTime? ClosingTime { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal OpeningCash { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal ClosingCash { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal ExpectedCash { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal DifferenceCash { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal TotalSales { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal TotalReturns { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal CardAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal CouponAmount { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    [StringLength(255)]
    public string Remarks { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("CashierShifts")]
    public virtual Branch Branch { get; set; }

    [InverseProperty("Shift")]
    public virtual ICollection<CashDenomination> CashDenominations { get; set; } = new List<CashDenomination>();

    [ForeignKey("CounterId")]
    [InverseProperty("CashierShifts")]
    public virtual Counter Counter { get; set; }

    [InverseProperty("Shift")]
    public virtual ICollection<CounterPayout> CounterPayouts { get; set; } = new List<CounterPayout>();

    [InverseProperty("Shift")]
    public virtual ICollection<SalesHeader> SalesHeaders { get; set; } = new List<SalesHeader>();

    [ForeignKey("UserId")]
    [InverseProperty("CashierShifts")]
    public virtual User User { get; set; }
}