// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("ShiftId", Name = "ix_CashDenominations_ShiftId")]
public partial class CashDenomination
{
    [Key]
    public int DenominationId { get; set; }

    public int ShiftId { get; set; }

    [Required]
    [StringLength(20)]
    public string EntryType { get; set; }

    public int Denomination2000 { get; set; }

    public int Denomination500 { get; set; }

    public int Denomination200 { get; set; }

    public int Denomination100 { get; set; }

    public int Denomination50 { get; set; }

    public int Denomination20 { get; set; }

    public int Denomination10 { get; set; }

    public int Denomination5 { get; set; }

    public int Denomination2 { get; set; }

    public int Denomination1 { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal CoinsAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal TotalCash { get; set; }

    [StringLength(255)]
    public string EnteredBy { get; set; }

    public DateTime EnteredOn { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("ShiftId")]
    [InverseProperty("CashDenominations")]
    public virtual CashierShift Shift { get; set; }
}