// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("CategoryCode", Name = "uq_Categories_CategoryCode", IsUnique = true)]
public partial class Category
{
    [Key]
    public int CategoryId { get; set; }

    [StringLength(255)]
    public string CategoryCode { get; set; }

    [StringLength(255)]
    public string CategoryName { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    public int DisplayOrder { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal DiscountPct { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [InverseProperty("Category")]
    public virtual ICollection<Item> Items { get; set; } = new List<Item>();

    [InverseProperty("Category")]
    public virtual ICollection<OfferItem> OfferItems { get; set; } = new List<OfferItem>();

    [InverseProperty("Category")]
    public virtual ICollection<SubCategory> SubCategories { get; set; } = new List<SubCategory>();

    [InverseProperty("Category")]
    public virtual ICollection<Supplier> Suppliers { get; set; } = new List<Supplier>();
}