// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("ColourName", Name = "uq_Colours_ColourName", IsUnique = true)]
public partial class Colour
{
    [Key]
    public int ColourId { get; set; }

    [StringLength(50)]
    public string ColourCode { get; set; }

    [Required]
    [StringLength(255)]
    public string ColourName { get; set; }

    [StringLength(10)]
    public string HexValue { get; set; }

    public bool IsActive { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [InverseProperty("Colour")]
    public virtual ICollection<ItemVariant> ItemVariants { get; set; } = new List<ItemVariant>();
}