// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("CompanyCode", Name = "uq_Companies_CompanyCode", IsUnique = true)]
public partial class Company
{
    [Key]
    public int CompanyId { get; set; }

    [StringLength(255)]
    public string CompanyCode { get; set; }

    [StringLength(255)]
    public string CompanyName { get; set; }

    [StringLength(255)]
    public string LegalName { get; set; }

    [StringLength(255)]
    public string ShortName { get; set; }

    [StringLength(255)]
    public string NatureOfBusiness { get; set; }

    [StringLength(255)]
    public string Gstin { get; set; }

    [StringLength(255)]
    public string Pan { get; set; }

    [StringLength(255)]
    public string TinNo { get; set; }

    [StringLength(255)]
    public string CstNo { get; set; }

    [StringLength(255)]
    public string Address1 { get; set; }

    [StringLength(255)]
    public string Address2 { get; set; }

    [StringLength(255)]
    public string Address3 { get; set; }

    [StringLength(255)]
    public string Place { get; set; }

    [StringLength(255)]
    public string Pincode { get; set; }

    [StringLength(255)]
    public string Phone { get; set; }

    [StringLength(255)]
    public string CellNo { get; set; }

    [StringLength(255)]
    public string FaxNo { get; set; }

    [StringLength(255)]
    public string Email { get; set; }

    [StringLength(255)]
    public string Website { get; set; }

    [Required]
    [StringLength(10)]
    public string CurrencyCode { get; set; }

    [Required]
    [StringLength(100)]
    public string Timezone { get; set; }

    [Column(TypeName = "date")]
    public DateTime? FinancialYearFrom { get; set; }

    [Column(TypeName = "date")]
    public DateTime? FinancialYearTo { get; set; }

    [StringLength(255)]
    public string PrintName { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [InverseProperty("Company")]
    public virtual ICollection<Branch> Branches { get; set; } = new List<Branch>();
}