// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("BranchId", Name = "ix_Counters_BranchId")]
[Index("BranchId", "CounterCode", Name = "uq_Counters_BranchCounterCode", IsUnique = true)]
public partial class Counter
{
    [Key]
    public int CounterId { get; set; }

    public int BranchId { get; set; }

    [StringLength(255)]
    public string CounterCode { get; set; }

    [StringLength(255)]
    public string CounterName { get; set; }

    [StringLength(255)]
    public string DeviceName { get; set; }

    [StringLength(255)]
    public string PrinterName { get; set; }

    [StringLength(255)]
    public string ScannerName { get; set; }

    public bool IsActive { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("Counters")]
    public virtual Branch Branch { get; set; }

    [InverseProperty("Counter")]
    public virtual ICollection<CashierShift> CashierShifts { get; set; } = new List<CashierShift>();

    [InverseProperty("Counter")]
    public virtual ICollection<HeldBill> HeldBills { get; set; } = new List<HeldBill>();

    [InverseProperty("Counter")]
    public virtual ICollection<SalesHeader> SalesHeaders { get; set; } = new List<SalesHeader>();
}