// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("BranchId", Name = "ix_CounterPayouts_BranchId")]
[Index("ShiftId", Name = "ix_CounterPayouts_ShiftId")]
public partial class CounterPayout
{
    [Key]
    public int PayoutId { get; set; }

    public int ShiftId { get; set; }

    public int BranchId { get; set; }

    public DateTime PayoutDate { get; set; }

    [StringLength(255)]
    public string RepName { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal Amount { get; set; }

    [StringLength(255)]
    public string Remarks { get; set; }

    [StringLength(255)]
    public string EnteredBy { get; set; }

    public bool IsActive { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("CounterPayouts")]
    public virtual Branch Branch { get; set; }

    [ForeignKey("ShiftId")]
    [InverseProperty("CounterPayouts")]
    public virtual CashierShift Shift { get; set; }
}