// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("CouponCode", Name = "uq_Coupons_CouponCode", IsUnique = true)]
public partial class Coupon
{
    [Key]
    public int CouponId { get; set; }

    [StringLength(255)]
    public string CouponCode { get; set; }

    [StringLength(255)]
    public string CouponType { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? DiscountValue { get; set; }

    [Column(TypeName = "date")]
    public DateTime? StartDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime? EndDate { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? MinBillAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? MaxDiscountAmount { get; set; }

    public int UsageLimit { get; set; }

    public int UsedCount { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }
}