// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("CustomerId", Name = "ix_CustomerLoyaltyTransactions_CustomerId")]
public partial class CustomerLoyaltyTransaction
{
    [Key]
    public int CustomerLoyaltyTxnId { get; set; }

    public int CustomerId { get; set; }

    [StringLength(100)]
    public string ReferenceType { get; set; }

    public int? ReferenceId { get; set; }

    public DateTime? TxnDate { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal PointsEarned { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal PointsRedeemed { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? BalancePoints { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? PointAmountValue { get; set; }

    [StringLength(255)]
    public string Narration { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? PointsPerAmount { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("CustomerLoyaltyTransactions")]
    public virtual Customer Customer { get; set; }
}