// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("CustomerCode", Name = "uq_Customers_CustomerCode", IsUnique = true)]
public partial class Customer
{
    [Key]
    public int CustomerId { get; set; }

    [StringLength(255)]
    public string CustomerCode { get; set; }

    [StringLength(255)]
    public string CustomerName { get; set; }

    [StringLength(255)]
    public string ShortName { get; set; }

    [StringLength(255)]
    public string PrintName { get; set; }

    [StringLength(255)]
    public string MobileNumber { get; set; }

    [StringLength(255)]
    public string PhoneNumber { get; set; }

    [StringLength(255)]
    public string Email { get; set; }

    [StringLength(255)]
    public string Address1 { get; set; }

    [StringLength(255)]
    public string Address2 { get; set; }

    [StringLength(255)]
    public string Address3 { get; set; }

    [StringLength(255)]
    public string AreaName { get; set; }

    [StringLength(255)]
    public string City { get; set; }

    [StringLength(255)]
    public string State { get; set; }

    [StringLength(255)]
    public string Country { get; set; }

    [StringLength(255)]
    public string Pincode { get; set; }

    [StringLength(255)]
    public string Gstin { get; set; }

    [StringLength(255)]
    public string Pan { get; set; }

    [StringLength(255)]
    public string TinNo { get; set; }

    [Column(TypeName = "date")]
    public DateTime? DateOfBirth { get; set; }

    [Column(TypeName = "date")]
    public DateTime? AnniversaryDate { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal OpeningBalance { get; set; }

    [StringLength(10)]
    public string OpeningBalType { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal CreditLimit { get; set; }

    public int DueDays { get; set; }

    [StringLength(100)]
    public string CustomerType { get; set; }

    [StringLength(50)]
    public string BillTypeDefault { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal LoyaltyPoints { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal SchemeAmount { get; set; }

    [StringLength(255)]
    public string RepName { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [InverseProperty("Customer")]
    public virtual ICollection<CustomerLedger> CustomerLedgers { get; set; } = new List<CustomerLedger>();

    [InverseProperty("Customer")]
    public virtual ICollection<CustomerLoyaltyTransaction> CustomerLoyaltyTransactions { get; set; } = new List<CustomerLoyaltyTransaction>();

    [InverseProperty("Customer")]
    public virtual ICollection<HeldBill> HeldBills { get; set; } = new List<HeldBill>();

    [InverseProperty("Customer")]
    public virtual ICollection<SalesHeader> SalesHeaders { get; set; } = new List<SalesHeader>();

    [InverseProperty("Customer")]
    public virtual ICollection<SalesReturn> SalesReturns { get; set; } = new List<SalesReturn>();
}