// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Table("DailySalesSummary")]
[Index("BranchId", "SummaryDate", Name = "ix_DailySalesSummary_BranchDate")]
public partial class DailySalesSummary
{
    [Key]
    public int DailySalesSummaryId { get; set; }

    public int BranchId { get; set; }

    [Column(TypeName = "date")]
    public DateTime? SummaryDate { get; set; }

    public int TotalBills { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal TotalQty { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal GrossAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal DiscountAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal TaxAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal NetAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal CashAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal CardAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal UpiAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal CouponAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal ReturnAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal PettyCash { get; set; }

    public DateTime CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("DailySalesSummaries")]
    public virtual Branch Branch { get; set; }
}