// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("AssignedUserId", Name = "ix_Devices_AssignedUserId")]
[Index("BranchId", Name = "ix_Devices_BranchId")]
public partial class Device
{
    [Key]
    public int DeviceId { get; set; }

    public int BranchId { get; set; }

    [StringLength(255)]
    public string DeviceCode { get; set; }

    [StringLength(255)]
    public string DeviceName { get; set; }

    [StringLength(255)]
    public string DeviceType { get; set; }

    [StringLength(255)]
    public string MacAddress { get; set; }

    [StringLength(255)]
    public string SerialNumber { get; set; }

    public int? AssignedUserId { get; set; }

    public bool IsActive { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("AssignedUserId")]
    [InverseProperty("Devices")]
    public virtual User AssignedUser { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("Devices")]
    public virtual Branch Branch { get; set; }

    [InverseProperty("Device")]
    public virtual ICollection<UserSession> UserSessions { get; set; } = new List<UserSession>();
}