// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("CategoryId", "ReferenceId", Name = "IX_Documents_Category_Reference")]
public partial class Document
{
    [Key]
    public int DocumentId { get; set; }

    [Required]
    public string ImageUrl { get; set; }

    public int CategoryId { get; set; }

    public int ReferenceId { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }
}