// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("NewSaleId", Name = "ix_Exchanges_NewSaleId")]
[Index("OriginalSaleId", Name = "ix_Exchanges_OriginalSaleId")]
[Index("ReturnId", Name = "ix_Exchanges_ReturnId")]
public partial class Exchange
{
    [Key]
    public int ExchangeId { get; set; }

    public int? OriginalSaleId { get; set; }

    public int? ReturnId { get; set; }

    public int? NewSaleId { get; set; }

    public DateTime? ExchangeDate { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal DifferenceAmount { get; set; }

    [StringLength(100)]
    public string SettlementStatus { get; set; }

    [StringLength(255)]
    public string Remarks { get; set; }

    public DateTime CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("NewSaleId")]
    [InverseProperty("ExchangeNewSales")]
    public virtual SalesHeader NewSale { get; set; }

    [ForeignKey("OriginalSaleId")]
    [InverseProperty("ExchangeOriginalSales")]
    public virtual SalesHeader OriginalSale { get; set; }

    [ForeignKey("ReturnId")]
    [InverseProperty("Exchanges")]
    public virtual SalesReturn Return { get; set; }
}