// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("BranchId", Name = "ix_HeldBills_BranchId")]
[Index("CustomerId", Name = "ix_HeldBills_CustomerId")]
public partial class HeldBill
{
    [Key]
    public int HeldBillId { get; set; }

    public int BranchId { get; set; }

    public int CounterId { get; set; }

    [StringLength(255)]
    public string HeldBillNo { get; set; }

    [StringLength(255)]
    public string SuspendName { get; set; }

    public int? CustomerId { get; set; }

    [StringLength(255)]
    public string Remarks { get; set; }

    public DateTime? HeldAt { get; set; }

    public int? HeldBy { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("HeldBills")]
    public virtual Branch Branch { get; set; }

    [ForeignKey("CounterId")]
    [InverseProperty("HeldBills")]
    public virtual Counter Counter { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("HeldBills")]
    public virtual Customer Customer { get; set; }

    [InverseProperty("HeldBill")]
    public virtual ICollection<HeldBillItem> HeldBillItems { get; set; } = new List<HeldBillItem>();

    [ForeignKey("HeldBy")]
    [InverseProperty("HeldBills")]
    public virtual User HeldByNavigation { get; set; }
}