// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("HeldBillId", Name = "ix_HeldBillItems_HeldBillId")]
[Index("ItemId", Name = "ix_HeldBillItems_ItemId")]
public partial class HeldBillItem
{
    [Key]
    public int HeldBillItemId { get; set; }

    public int HeldBillId { get; set; }

    public int ItemId { get; set; }

    public int? ItemVariantId { get; set; }

    [StringLength(255)]
    public string BarcodeValue { get; set; }

    [StringLength(255)]
    public string ColourName { get; set; }

    [StringLength(255)]
    public string SizeName { get; set; }

    [StringLength(255)]
    public string StyleNo { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal Qty { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal UnitRate { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal DiscountAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal OfferDiscountAmount { get; set; }

    public int? TaxId { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal TaxAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal LineTotal { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("HeldBillId")]
    [InverseProperty("HeldBillItems")]
    public virtual HeldBill HeldBill { get; set; }

    [ForeignKey("ItemId")]
    [InverseProperty("HeldBillItems")]
    public virtual Item Item { get; set; }

    [ForeignKey("ItemVariantId")]
    [InverseProperty("HeldBillItems")]
    public virtual ItemVariant ItemVariant { get; set; }

    [ForeignKey("TaxId")]
    [InverseProperty("HeldBillItems")]
    public virtual TaxMaster Tax { get; set; }
}