// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("ItemId", Name = "ix_ItemAlternateBarcodes_ItemId")]
[Index("ItemVariantId", Name = "ix_ItemAlternateBarcodes_ItemVariantId")]
public partial class ItemAlternateBarcode
{
    [Key]
    public int ItemAlternateBarcodeId { get; set; }

    public int ItemId { get; set; }

    public int? ItemVariantId { get; set; }

    [Required]
    [StringLength(255)]
    public string BarcodeValue { get; set; }

    [StringLength(100)]
    public string BarcodeType { get; set; }

    public bool IsPrimary { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("ItemId")]
    [InverseProperty("ItemAlternateBarcodes")]
    public virtual Item Item { get; set; }

    [ForeignKey("ItemVariantId")]
    [InverseProperty("ItemAlternateBarcodes")]
    public virtual ItemVariant ItemVariant { get; set; }
}