// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Table("ItemPriceHistory")]
[Index("ChangedBy", Name = "ix_ItemPriceHistory_ChangedBy")]
[Index("ItemId", Name = "ix_ItemPriceHistory_ItemId")]
public partial class ItemPriceHistory
{
    [Key]
    public int ItemPriceHistoryId { get; set; }

    public int ItemId { get; set; }

    public int? ItemVariantId { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? OldPurchasePrice { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? NewPurchasePrice { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? OldSellingPrice { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? NewSellingPrice { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? OldMrp { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? NewMrp { get; set; }

    public DateTime ChangedOn { get; set; }

    public int? ChangedBy { get; set; }

    [StringLength(255)]
    public string ChangedByName { get; set; }

    [StringLength(255)]
    public string BatchNo { get; set; }

    [StringLength(255)]
    public string Reason { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("ChangedBy")]
    [InverseProperty("ItemPriceHistories")]
    public virtual User ChangedByNavigation { get; set; }

    [ForeignKey("ItemId")]
    [InverseProperty("ItemPriceHistories")]
    public virtual Item Item { get; set; }

    [ForeignKey("ItemVariantId")]
    [InverseProperty("ItemPriceHistories")]
    public virtual ItemVariant ItemVariant { get; set; }
}