// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("BarcodeValue", Name = "ix_Items_BarcodeValue")]
[Index("BranchId", Name = "ix_Items_BranchId")]
[Index("BrandId", Name = "ix_Items_BrandId")]
[Index("CategoryId", Name = "ix_Items_CategoryId")]
[Index("Pcode", Name = "ix_Items_PCode")]
[Index("PurchaseTaxId", Name = "ix_Items_PurchaseTaxId")]
[Index("SalesTaxId", Name = "ix_Items_SalesTaxId")]
[Index("SubCategoryId", Name = "ix_Items_SubCategoryId")]
[Index("UnitId", Name = "ix_Items_UnitId")]
[Index("BranchId", "ItemCode", Name = "uq_Items_BranchItemCode", IsUnique = true)]
public partial class Item
{
    [Key]
    public int ItemId { get; set; }

    public int? BranchId { get; set; }

    [StringLength(255)]
    public string ItemCode { get; set; }

    [Column("PCode")]
    [StringLength(50)]
    public string Pcode { get; set; }

    [StringLength(255)]
    public string BarcodeValue { get; set; }

    [StringLength(255)]
    public string BarcodePrintName { get; set; }

    [StringLength(255)]
    public string ItemName { get; set; }

    [StringLength(255)]
    public string ShortName { get; set; }

    public int? CategoryId { get; set; }

    public int? SubCategoryId { get; set; }

    public int? BrandId { get; set; }

    public int? UnitId { get; set; }

    public int? SalesTaxId { get; set; }

    public int? PurchaseTaxId { get; set; }

    [StringLength(255)]
    public string HsnCode { get; set; }

    [Required]
    [StringLength(100)]
    public string ItemType { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal PurchasePrice { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal CostPrice { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal CurrentCost { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal SellingPrice { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal SpecialPrice { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal Mrp { get; set; }

    public bool IsPriceInclusiveOfTax { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal DiscountPct { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal PackingSize { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal OpeningStockQty { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal ClosingStockQty { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal MaxStockQty { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal MinStockQty { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal ReorderLevel { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal ReorderQty { get; set; }

    [StringLength(255)]
    public string ShelfLocation { get; set; }

    public bool IsSpecialItem { get; set; }

    public bool IsFastMoving { get; set; }

    public bool IsSlowMoving { get; set; }

    public bool IsStockTracked { get; set; }

    public bool HasVariants { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal LoyaltyPointsPerUnit { get; set; }

    [StringLength(255)]
    public string DefaultAgentName { get; set; }

    [StringLength(500)]
    public string Remarks { get; set; }

    public string Description { get; set; }

    [StringLength(500)]
    public string ImageUrl { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [InverseProperty("Item")]
    public virtual ICollection<BarcodePrintBatchItem> BarcodePrintBatchItems { get; set; } = new List<BarcodePrintBatchItem>();

    [ForeignKey("BranchId")]
    [InverseProperty("Items")]
    public virtual Branch Branch { get; set; }

    [ForeignKey("BrandId")]
    [InverseProperty("Items")]
    public virtual Brand Brand { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("Items")]
    public virtual Category Category { get; set; }

    [InverseProperty("Item")]
    public virtual ICollection<HeldBillItem> HeldBillItems { get; set; } = new List<HeldBillItem>();

    [InverseProperty("Item")]
    public virtual ICollection<ItemAlternateBarcode> ItemAlternateBarcodes { get; set; } = new List<ItemAlternateBarcode>();

    [InverseProperty("Item")]
    public virtual ICollection<ItemPriceHistory> ItemPriceHistories { get; set; } = new List<ItemPriceHistory>();

    [InverseProperty("Item")]
    public virtual ICollection<ItemSupplier> ItemSuppliers { get; set; } = new List<ItemSupplier>();

    [InverseProperty("Item")]
    public virtual ICollection<ItemVariant> ItemVariants { get; set; } = new List<ItemVariant>();

    [InverseProperty("FreeItem")]
    public virtual ICollection<OfferCondition> OfferConditions { get; set; } = new List<OfferCondition>();

    [InverseProperty("Item")]
    public virtual ICollection<OfferItem> OfferItems { get; set; } = new List<OfferItem>();

    [InverseProperty("Item")]
    public virtual ICollection<PurchaseItem> PurchaseItems { get; set; } = new List<PurchaseItem>();

    [ForeignKey("PurchaseTaxId")]
    [InverseProperty("ItemPurchaseTaxes")]
    public virtual TaxMaster PurchaseTax { get; set; }

    [InverseProperty("FreeItem")]
    public virtual ICollection<SalesItem> SalesItemFreeItems { get; set; } = new List<SalesItem>();

    [InverseProperty("Item")]
    public virtual ICollection<SalesItem> SalesItemItems { get; set; } = new List<SalesItem>();

    [InverseProperty("Item")]
    public virtual ICollection<SalesReturnItem> SalesReturnItems { get; set; } = new List<SalesReturnItem>();

    [ForeignKey("SalesTaxId")]
    [InverseProperty("ItemSalesTaxes")]
    public virtual TaxMaster SalesTax { get; set; }

    [InverseProperty("BuyItem")]
    public virtual ICollection<SchemeMaster> SchemeMasterBuyItems { get; set; } = new List<SchemeMaster>();

    [InverseProperty("FreeItem")]
    public virtual ICollection<SchemeMaster> SchemeMasterFreeItems { get; set; } = new List<SchemeMaster>();

    [InverseProperty("Item")]
    public virtual ICollection<StockAdjustmentItem> StockAdjustmentItems { get; set; } = new List<StockAdjustmentItem>();

    [InverseProperty("Item")]
    public virtual ICollection<StockLedger> StockLedgers { get; set; } = new List<StockLedger>();

    [InverseProperty("Item")]
    public virtual ICollection<StockTransferItem> StockTransferItems { get; set; } = new List<StockTransferItem>();

    [ForeignKey("SubCategoryId")]
    [InverseProperty("Items")]
    public virtual SubCategory SubCategory { get; set; }

    [ForeignKey("UnitId")]
    [InverseProperty("Items")]
    public virtual Unit Unit { get; set; }
}