// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("BarcodeValue", Name = "ix_ItemVariants_BarcodeValue")]
[Index("ItemId", "ColourId", "SizeId", Name = "ix_ItemVariants_ColourSize")]
[Index("ItemId", Name = "ix_ItemVariants_ItemId")]
[Index("StyleNo", Name = "ix_ItemVariants_StyleNo")]
public partial class ItemVariant
{
    [Key]
    public int ItemVariantId { get; set; }

    public int ItemId { get; set; }

    public int? ColourId { get; set; }

    public int? SizeId { get; set; }

    [StringLength(255)]
    public string ColourName { get; set; }

    [StringLength(255)]
    public string SizeName { get; set; }

    [StringLength(255)]
    public string StyleNo { get; set; }

    [StringLength(255)]
    public string SupplierName { get; set; }

    [StringLength(255)]
    public string BarcodeValue { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? PurchasePrice { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? SellingPrice { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? Mrp { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? CostPrice { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal StockQty { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [InverseProperty("ItemVariant")]
    public virtual ICollection<BarcodePrintBatchItem> BarcodePrintBatchItems { get; set; } = new List<BarcodePrintBatchItem>();

    [ForeignKey("ColourId")]
    [InverseProperty("ItemVariants")]
    public virtual Colour Colour { get; set; }

    [InverseProperty("ItemVariant")]
    public virtual ICollection<HeldBillItem> HeldBillItems { get; set; } = new List<HeldBillItem>();

    [ForeignKey("ItemId")]
    [InverseProperty("ItemVariants")]
    public virtual Item Item { get; set; }

    [InverseProperty("ItemVariant")]
    public virtual ICollection<ItemAlternateBarcode> ItemAlternateBarcodes { get; set; } = new List<ItemAlternateBarcode>();

    [InverseProperty("ItemVariant")]
    public virtual ICollection<ItemPriceHistory> ItemPriceHistories { get; set; } = new List<ItemPriceHistory>();

    [InverseProperty("ItemVariant")]
    public virtual ICollection<PurchaseItem> PurchaseItems { get; set; } = new List<PurchaseItem>();

    [InverseProperty("ItemVariant")]
    public virtual ICollection<SalesItem> SalesItems { get; set; } = new List<SalesItem>();

    [InverseProperty("ItemVariant")]
    public virtual ICollection<SalesReturnItem> SalesReturnItems { get; set; } = new List<SalesReturnItem>();

    [ForeignKey("SizeId")]
    [InverseProperty("ItemVariants")]
    public virtual Size Size { get; set; }

    [InverseProperty("ItemVariant")]
    public virtual ICollection<StockAdjustmentItem> StockAdjustmentItems { get; set; } = new List<StockAdjustmentItem>();

    [InverseProperty("ItemVariant")]
    public virtual ICollection<StockLedger> StockLedgers { get; set; } = new List<StockLedger>();

    [InverseProperty("ItemVariant")]
    public virtual ICollection<StockTransferItem> StockTransferItems { get; set; } = new List<StockTransferItem>();
}