// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("ItemId", Name = "ix_ItemSuppliers_ItemId")]
[Index("SupplierId", Name = "ix_ItemSuppliers_SupplierId")]
public partial class ItemSupplier
{
    [Key]
    public int ItemSupplierId { get; set; }

    public int ItemId { get; set; }

    public int SupplierId { get; set; }

    [StringLength(255)]
    public string SupplierItemCode { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal LastPurchasePrice { get; set; }

    public bool PreferredSupplier { get; set; }

    public int LeadTimeDays { get; set; }

    public bool IsActive { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("ItemId")]
    [InverseProperty("ItemSuppliers")]
    public virtual Item Item { get; set; }

    [ForeignKey("SupplierId")]
    [InverseProperty("ItemSuppliers")]
    public virtual Supplier Supplier { get; set; }
}