// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

public partial class LoyaltyProgram
{
    [Key]
    public int LoyaltyProgramId { get; set; }

    [StringLength(255)]
    public string ProgramName { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal PointsPerAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal RedeemValuePerPoint { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal MinPointsToRedeem { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }
}