// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("BrandId", Name = "ix_OfferItems_BrandId")]
[Index("CategoryId", Name = "ix_OfferItems_CategoryId")]
[Index("ItemId", Name = "ix_OfferItems_ItemId")]
[Index("OfferId", Name = "ix_OfferItems_OfferId")]
public partial class OfferItem
{
    [Key]
    public int OfferItemId { get; set; }

    public int OfferId { get; set; }

    public int? ItemId { get; set; }

    public int? CategoryId { get; set; }

    public int? BrandId { get; set; }

    [StringLength(100)]
    public string ApplicableType { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("BrandId")]
    [InverseProperty("OfferItems")]
    public virtual Brand Brand { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("OfferItems")]
    public virtual Category Category { get; set; }

    [ForeignKey("ItemId")]
    [InverseProperty("OfferItems")]
    public virtual Item Item { get; set; }

    [ForeignKey("OfferId")]
    [InverseProperty("OfferItems")]
    public virtual Offer Offer { get; set; }
}