// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("FreeItemId", Name = "ix_OfferConditions_FreeItemId")]
[Index("OfferId", Name = "ix_OfferConditions_OfferId")]
public partial class OfferCondition
{
    [Key]
    public int OfferConditionId { get; set; }

    public int OfferId { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? BuyQty { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? GetQty { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? MinQty { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? MinAmount { get; set; }

    [StringLength(100)]
    public string DiscountType { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? DiscountValue { get; set; }

    public int? FreeItemId { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? FreeQty { get; set; }

    public bool ApplyPerSet { get; set; }

    public int? MaxApplyCount { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [Column("BuyXGetYStrategy")]
    [StringLength(50)]
    public string BuyXgetYstrategy { get; set; }

    [ForeignKey("FreeItemId")]
    [InverseProperty("OfferConditions")]
    public virtual Item FreeItem { get; set; }

    [ForeignKey("OfferId")]
    [InverseProperty("OfferConditions")]
    public virtual Offer Offer { get; set; }
}