// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("OfferCode", Name = "uq_Offers_OfferCode", IsUnique = true)]
public partial class Offer
{
    [Key]
    public int OfferId { get; set; }

    [StringLength(255)]
    public string OfferCode { get; set; }

    [StringLength(255)]
    public string OfferName { get; set; }

    [StringLength(100)]
    public string OfferType { get; set; }

    [StringLength(500)]
    public string Description { get; set; }

    [Column(TypeName = "date")]
    public DateTime? StartDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime? EndDate { get; set; }

    public TimeSpan? StartTime { get; set; }

    public TimeSpan? EndTime { get; set; }

    public int Priority { get; set; }

    public bool IsAutoApply { get; set; }

    public bool IsCouponRequired { get; set; }

    [StringLength(255)]
    public string CouponCode { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? MaxDiscountAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? MinBillAmount { get; set; }

    [StringLength(100)]
    public string ApplicableScope { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [InverseProperty("Offer")]
    public virtual ICollection<AppliedOffersLog> AppliedOffersLogs { get; set; } = new List<AppliedOffersLog>();

    [InverseProperty("Offer")]
    public virtual ICollection<OfferCondition> OfferConditions { get; set; } = new List<OfferCondition>();

    [InverseProperty("Offer")]
    public virtual ICollection<OfferItem> OfferItems { get; set; } = new List<OfferItem>();

    [InverseProperty("Offer")]
    public virtual ICollection<SalesItem> SalesItems { get; set; } = new List<SalesItem>();
}