// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("PaymentModeCode", Name = "uq_PaymentModes_PaymentModeCode", IsUnique = true)]
public partial class PaymentMode
{
    [Key]
    public int PaymentModeId { get; set; }

    [StringLength(255)]
    public string PaymentModeCode { get; set; }

    [StringLength(255)]
    public string PaymentModeName { get; set; }

    public bool IsCash { get; set; }

    public bool IsDigital { get; set; }

    public bool RequiresReferenceNo { get; set; }

    public bool IsActive { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [InverseProperty("PaymentMode")]
    public virtual ICollection<PurchaseHeader> PurchaseHeaders { get; set; } = new List<PurchaseHeader>();

    [InverseProperty("PaymentMode")]
    public virtual ICollection<PurchasePayment> PurchasePayments { get; set; } = new List<PurchasePayment>();

    [InverseProperty("RefundMode")]
    public virtual ICollection<PurchaseReturn> PurchaseReturns { get; set; } = new List<PurchaseReturn>();

    [InverseProperty("PaymentMode")]
    public virtual ICollection<SalesPayment> SalesPayments { get; set; } = new List<SalesPayment>();

    [InverseProperty("RefundMode")]
    public virtual ICollection<SalesReturn> SalesReturns { get; set; } = new List<SalesReturn>();
}