// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("PermissionCode", Name = "uq_Permissions_PermissionCode", IsUnique = true)]
public partial class Permission
{
    [Key]
    public int PermissionId { get; set; }

    [StringLength(255)]
    public string PermissionCode { get; set; }

    [StringLength(255)]
    public string PermissionName { get; set; }

    [StringLength(255)]
    public string ModuleName { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [InverseProperty("Permission")]
    public virtual ICollection<RolePermission> RolePermissions { get; set; } = new List<RolePermission>();
}