// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("ItemId", Name = "ix_PurchaseItems_ItemId")]
[Index("ItemVariantId", Name = "ix_PurchaseItems_ItemVariantId")]
[Index("PurchaseId", Name = "ix_PurchaseItems_PurchaseId")]
[Index("TaxId", Name = "ix_PurchaseItems_TaxId")]
public partial class PurchaseItem
{
    [Key]
    public int PurchaseItemId { get; set; }

    public int PurchaseId { get; set; }

    public int? ItemId { get; set; }

    public int? ItemVariantId { get; set; }

    [StringLength(255)]
    public string BarcodeValue { get; set; }

    [StringLength(255)]
    public string ColourName { get; set; }

    [StringLength(255)]
    public string SizeName { get; set; }

    [StringLength(255)]
    public string StyleNo { get; set; }

    [StringLength(255)]
    public string SupplierName { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal Qty { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal FreeQty { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal PackingQty { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal PackingSize { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal PurchaseRate { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal Mrp { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal SellingRate { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal TradeDiscountPct { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal TradeDiscountAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal DiscountPercent { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal DiscountAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal CostPrice { get; set; }

    public int? TaxId { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal TaxableAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal CgstAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal SgstAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal IgstAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal CessAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal LineTotal { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal ReceivedQty { get; set; }

    [ForeignKey("ItemId")]
    [InverseProperty("PurchaseItems")]
    public virtual Item Item { get; set; }

    [ForeignKey("ItemVariantId")]
    [InverseProperty("PurchaseItems")]
    public virtual ItemVariant ItemVariant { get; set; }

    [ForeignKey("PurchaseId")]
    [InverseProperty("PurchaseItems")]
    public virtual PurchaseHeader Purchase { get; set; }

    [ForeignKey("TaxId")]
    [InverseProperty("PurchaseItems")]
    public virtual TaxMaster Tax { get; set; }
}