// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("BranchId", Name = "ix_PurchaseHeaders_BranchId")]
[Index("GrnType", Name = "ix_PurchaseHeaders_GrnType")]
[Index("PurchaseDate", Name = "ix_PurchaseHeaders_PurchaseDate")]
[Index("SupplierId", Name = "ix_PurchaseHeaders_SupplierId")]
public partial class PurchaseHeader
{
    [Key]
    public int PurchaseId { get; set; }

    public int BranchId { get; set; }

    public int? SupplierId { get; set; }

    [Required]
    [StringLength(50)]
    public string GrnType { get; set; }

    [StringLength(255)]
    public string PurchaseNo { get; set; }

    [StringLength(255)]
    public string SupplierInvoiceNo { get; set; }

    [Column(TypeName = "date")]
    public DateTime? PurchaseDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime? InvoiceDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime? DueDate { get; set; }

    [StringLength(255)]
    public string OrderNo { get; set; }

    [Column(TypeName = "date")]
    public DateTime? OrderDate { get; set; }

    [StringLength(255)]
    public string DcNo { get; set; }

    [Column(TypeName = "date")]
    public DateTime? DcDate { get; set; }

    [StringLength(255)]
    public string LrNo { get; set; }

    [Column(TypeName = "date")]
    public DateTime? LrDate { get; set; }

    [StringLength(255)]
    public string VehicleNo { get; set; }

    [StringLength(255)]
    public string CarrierName { get; set; }

    [StringLength(255)]
    public string RepName { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal GrossAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal TradeDiscountAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal SpecialDiscountAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal PackingCharge { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal OnAccountAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal OnAccountAdjusted { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal TaxableAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal CgstAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal SgstAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal IgstAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal CessAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal RoundOffAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal NetAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal InvoiceAmount { get; set; }

    [StringLength(50)]
    public string PaymentStatus { get; set; }

    [StringLength(50)]
    public string PaymentTerms { get; set; }

    public int? PaymentModeId { get; set; }

    [StringLength(500)]
    public string Remarks { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int? LocationId { get; set; }

    public int? PurchaseStatusId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ExpectedDeliveryDate { get; set; }

    [StringLength(255)]
    public string PurChaseOrderNumber { get; set; }

    public int? UpdatedBy { get; set; }

    public string BillingAddress { get; set; }

    public string NotesToSupplier { get; set; }

    public string TermsAndConditions { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("PurchaseHeaders")]
    public virtual Branch Branch { get; set; }

    [ForeignKey("LocationId")]
    [InverseProperty("PurchaseHeaders")]
    public virtual Location Location { get; set; }

    [ForeignKey("PaymentModeId")]
    [InverseProperty("PurchaseHeaders")]
    public virtual PaymentMode PaymentMode { get; set; }

    [InverseProperty("Purchase")]
    public virtual ICollection<PurchaseActivityLog> PurchaseActivityLogs { get; set; } = new List<PurchaseActivityLog>();

    [InverseProperty("Purchase")]
    public virtual ICollection<PurchaseAdditionalCharge> PurchaseAdditionalCharges { get; set; } = new List<PurchaseAdditionalCharge>();

    [InverseProperty("Purchase")]
    public virtual ICollection<PurchaseItem> PurchaseItems { get; set; } = new List<PurchaseItem>();

    [InverseProperty("Purchase")]
    public virtual ICollection<PurchasePayment> PurchasePayments { get; set; } = new List<PurchasePayment>();

    [InverseProperty("Purchase")]
    public virtual ICollection<PurchaseReturn> PurchaseReturns { get; set; } = new List<PurchaseReturn>();

    [ForeignKey("PurchaseStatusId")]
    [InverseProperty("PurchaseHeaders")]
    public virtual PurchaseStatus PurchaseStatus { get; set; }

    [ForeignKey("SupplierId")]
    [InverseProperty("PurchaseHeaders")]
    public virtual Supplier Supplier { get; set; }
}