// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("PaymentModeId", Name = "ix_PurchasePayments_PaymentModeId")]
[Index("PurchaseId", Name = "ix_PurchasePayments_PurchaseId")]
public partial class PurchasePayment
{
    [Key]
    public int PurchasePaymentId { get; set; }

    public int PurchaseId { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal PaidAmount { get; set; }

    public DateTime? PaymentDate { get; set; }

    public int? PaymentModeId { get; set; }

    [StringLength(255)]
    public string ReferenceNo { get; set; }

    [StringLength(255)]
    public string BankName { get; set; }

    [StringLength(255)]
    public string Remarks { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("PaymentModeId")]
    [InverseProperty("PurchasePayments")]
    public virtual PaymentMode PaymentMode { get; set; }

    [ForeignKey("PurchaseId")]
    [InverseProperty("PurchasePayments")]
    public virtual PurchaseHeader Purchase { get; set; }
}