// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Table("PurchaseStatus")]
public partial class PurchaseStatus
{
    [Key]
    public int PurchaseStatusId { get; set; }

    [Required]
    [Column("PurchaseStatus")]
    [StringLength(255)]
    public string PurchaseStatus1 { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedOn { get; set; }

    public bool IsActive { get; set; }


    [InverseProperty("PurchaseStatus")]
    public virtual ICollection<PurchaseHeader> PurchaseHeaders { get; set; } = new List<PurchaseHeader>();
}