// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

public partial class PurchaseReturn
{
    [Key]
    public int PurchaseReturnId { get; set; }

    public int? PurchaseId { get; set; }

    public int BranchId { get; set; }

    public int? SupplierId { get; set; }

    [StringLength(255)]
    public string ReturnNo { get; set; }

    [Column(TypeName = "date")]
    public DateTime? ReturnDate { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal GrossAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal TaxAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal NetAmount { get; set; }

    public int? RefundModeId { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal ReturnAmount { get; set; }

    [StringLength(255)]
    public string Remarks { get; set; }

    public DateTime CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("PurchaseReturns")]
    public virtual Branch Branch { get; set; }

    [ForeignKey("PurchaseId")]
    [InverseProperty("PurchaseReturns")]
    public virtual PurchaseHeader Purchase { get; set; }

    [ForeignKey("RefundModeId")]
    [InverseProperty("PurchaseReturns")]
    public virtual PaymentMode RefundMode { get; set; }

    [ForeignKey("SupplierId")]
    [InverseProperty("PurchaseReturns")]
    public virtual Supplier Supplier { get; set; }
}