// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("PurchaseId", Name = "IX_PurchaseActivityLogs_PurchaseId")]
public partial class PurchaseActivityLog
{
    [Key]
    public int LogId { get; set; }

    public int PurchaseId { get; set; }

    [Required]
    [StringLength(100)]
    public string ActionName { get; set; }

    public string Description { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    [ForeignKey("PurchaseId")]
    [InverseProperty("PurchaseActivityLogs")]
    public virtual PurchaseHeader Purchase { get; set; }
}