// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

public partial class PurchaseAdditionalCharge
{
    [Key]
    public int PuchaseAdditionalChargeId { get; set; }

    public int PurchaseId { get; set; }

    [StringLength(256)]
    public string AdditionalChargeName { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? AdditionalTaxAmount { get; set; }

    public int? TaxId { get; set; }

    [StringLength(50)]
    public string AdditionalTax { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedOn { get; set; }

    public int? UpdatedBy { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? Amount { get; set; }

    [ForeignKey("PurchaseId")]
    [InverseProperty("PurchaseAdditionalCharges")]
    public virtual PurchaseHeader Purchase { get; set; }

    [ForeignKey("TaxId")]
    [InverseProperty("PurchaseAdditionalCharges")]
    public virtual TaxMaster Tax { get; set; }
}