// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

public partial class RefreshToken
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(200)]
    public string Token { get; set; }

    [Required]
    [StringLength(450)]
    public string UserId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Expires { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    [Required]
    [StringLength(100)]
    public string CreatedByIp { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Revoked { get; set; }

    [StringLength(100)]
    public string RevokedByIp { get; set; }

    [StringLength(200)]
    public string ReplacedByToken { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }
}