// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("ItemId", Name = "ix_SalesReturnItems_ItemId")]
[Index("SalesReturnId", Name = "ix_SalesReturnItems_ReturnId")]
[Index("SaleItemId", Name = "ix_SalesReturnItems_SaleItemId")]
public partial class SalesReturnItem
{
    [Key]
    public int SalesReturnItemId { get; set; }

    public int SalesReturnId { get; set; }

    public int? SaleItemId { get; set; }

    public int ItemId { get; set; }

    public int? ItemVariantId { get; set; }

    [StringLength(255)]
    public string ColourName { get; set; }

    [StringLength(255)]
    public string SizeName { get; set; }

    [StringLength(255)]
    public string StyleNo { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal ReturnQty { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal UnitRate { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal DiscountAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal TaxAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal LineTotal { get; set; }

    [StringLength(255)]
    public string Reason { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("ItemId")]
    [InverseProperty("SalesReturnItems")]
    public virtual Item Item { get; set; }

    [ForeignKey("ItemVariantId")]
    [InverseProperty("SalesReturnItems")]
    public virtual ItemVariant ItemVariant { get; set; }

    [ForeignKey("SaleItemId")]
    [InverseProperty("SalesReturnItems")]
    public virtual SalesItem SaleItem { get; set; }

    [ForeignKey("SalesReturnId")]
    [InverseProperty("SalesReturnItems")]
    public virtual SalesReturn SalesReturn { get; set; }
}