// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("ItemId", Name = "ix_SalesItems_ItemId")]
[Index("ItemVariantId", Name = "ix_SalesItems_ItemVariantId")]
[Index("OfferId", Name = "ix_SalesItems_OfferId")]
[Index("SaleId", Name = "ix_SalesItems_SaleId")]
[Index("TaxId", Name = "ix_SalesItems_TaxId")]
public partial class SalesItem
{
    [Key]
    public int SaleItemId { get; set; }

    public int SaleId { get; set; }

    public int? ItemId { get; set; }

    public int? ItemVariantId { get; set; }

    [StringLength(255)]
    public string BarcodeValue { get; set; }

    [StringLength(255)]
    public string ItemNameSnapshot { get; set; }

    [StringLength(255)]
    public string ColourName { get; set; }

    [StringLength(255)]
    public string SizeName { get; set; }

    [StringLength(255)]
    public string StyleNo { get; set; }

    [StringLength(255)]
    public string SupplierName { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal Qty { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal FreeQty { get; set; }

    [StringLength(50)]
    public string PackingQty { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal UnitRate { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal Mrp { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal PurchaseRate { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal CostPrice { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal DiscountPercent { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal DiscountAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal BeforeDiscountAmount { get; set; }

    public int? OfferId { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal OfferDiscountAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal EffectiveUnitRate { get; set; }

    public int? FreeItemId { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal FreeItemQty { get; set; }

    public int? TaxId { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal TaxPercent { get; set; }

    public bool IsTaxInclusive { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal TaxableAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal CgstAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal SgstAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal IgstAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal CessAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal LineTotal { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal ItemLoyaltyPoints { get; set; }

    [StringLength(50)]
    public string LineStatus { get; set; }

    public DateTime CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [InverseProperty("SaleItem")]
    public virtual ICollection<AppliedOffersLog> AppliedOffersLogs { get; set; } = new List<AppliedOffersLog>();

    [ForeignKey("FreeItemId")]
    [InverseProperty("SalesItemFreeItems")]
    public virtual Item FreeItem { get; set; }

    [ForeignKey("ItemId")]
    [InverseProperty("SalesItemItems")]
    public virtual Item Item { get; set; }

    [ForeignKey("ItemVariantId")]
    [InverseProperty("SalesItems")]
    public virtual ItemVariant ItemVariant { get; set; }

    [ForeignKey("OfferId")]
    [InverseProperty("SalesItems")]
    public virtual Offer Offer { get; set; }

    [ForeignKey("SaleId")]
    [InverseProperty("SalesItems")]
    public virtual SalesHeader Sale { get; set; }

    [InverseProperty("SaleItem")]
    public virtual ICollection<SalesReturnItem> SalesReturnItems { get; set; } = new List<SalesReturnItem>();

    [ForeignKey("TaxId")]
    [InverseProperty("SalesItems")]
    public virtual TaxMaster Tax { get; set; }
}