// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("PaymentModeId", Name = "ix_SalesPayments_PaymentModeId")]
[Index("SaleId", Name = "ix_SalesPayments_SaleId")]
public partial class SalesPayment
{
    [Key]
    public int SalePaymentId { get; set; }

    public int SaleId { get; set; }

    public int PaymentModeId { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal PaidAmount { get; set; }

    [StringLength(255)]
    public string ReferenceNo { get; set; }

    [StringLength(255)]
    public string BankName { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal ServiceChargePct { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal ServiceChargeAmt { get; set; }

    public DateTime? PaymentDate { get; set; }

    [StringLength(255)]
    public string Remarks { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("PaymentModeId")]
    [InverseProperty("SalesPayments")]
    public virtual PaymentMode PaymentMode { get; set; }

    [ForeignKey("SaleId")]
    [InverseProperty("SalesPayments")]
    public virtual SalesHeader Sale { get; set; }
}