// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("BillDate", Name = "ix_SalesHeaders_BillDate")]
[Index("BillType", Name = "ix_SalesHeaders_BillType")]
[Index("BranchId", Name = "ix_SalesHeaders_BranchId")]
[Index("CounterId", Name = "ix_SalesHeaders_CounterId")]
[Index("CustomerId", Name = "ix_SalesHeaders_CustomerId")]
[Index("PaymentTerms", Name = "ix_SalesHeaders_PaymentTerms")]
[Index("ShiftId", Name = "ix_SalesHeaders_ShiftId")]
public partial class SalesHeader
{
    [Key]
    public int SaleId { get; set; }

    public int BranchId { get; set; }

    public int? CounterId { get; set; }

    public int? ShiftId { get; set; }

    [Required]
    [StringLength(50)]
    public string BillType { get; set; }

    [StringLength(255)]
    public string SaleNo { get; set; }

    [StringLength(255)]
    public string BillNo { get; set; }

    public DateTime? BillDate { get; set; }

    public int? CustomerId { get; set; }

    [StringLength(100)]
    public string CustomerType { get; set; }

    [StringLength(255)]
    public string CustomerNameSnapshot { get; set; }

    [StringLength(255)]
    public string CustomerPhoneSnapshot { get; set; }

    [StringLength(50)]
    public string PaymentTerms { get; set; }

    [Column(TypeName = "date")]
    public DateTime? DueDate { get; set; }

    [StringLength(255)]
    public string ReturnedBillNo { get; set; }

    [StringLength(255)]
    public string OrderNo { get; set; }

    [StringLength(255)]
    public string DcNo { get; set; }

    [StringLength(255)]
    public string LrNo { get; set; }

    [StringLength(255)]
    public string TransportName { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal GrossAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal ItemDiscountAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal BillDiscountPct { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal BillDiscountAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal OfferDiscountAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal PackingCharge { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal OnAccountAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal OnAccountAdjusted { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal PointAdjustment { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal TaxableAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal CgstAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal SgstAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal IgstAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal CessAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal RoundOffAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal NetAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal ReceivedAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal BalanceAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal TotalQty { get; set; }

    [StringLength(50)]
    public string PaymentStatus { get; set; }

    [StringLength(50)]
    public string SaleStatus { get; set; }

    public bool IsCancelled { get; set; }

    [StringLength(255)]
    public string SalesmanName { get; set; }

    public int? CreatedBy { get; set; }

    [StringLength(500)]
    public string Remarks { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int? UpdatedBy { get; set; }

    [InverseProperty("Sale")]
    public virtual ICollection<AppliedOffersLog> AppliedOffersLogs { get; set; } = new List<AppliedOffersLog>();

    [ForeignKey("BranchId")]
    [InverseProperty("SalesHeaders")]
    public virtual Branch Branch { get; set; }

    [ForeignKey("CounterId")]
    [InverseProperty("SalesHeaders")]
    public virtual Counter Counter { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("SalesHeaders")]
    public virtual Customer Customer { get; set; }

    [InverseProperty("NewSale")]
    public virtual ICollection<Exchange> ExchangeNewSales { get; set; } = new List<Exchange>();

    [InverseProperty("OriginalSale")]
    public virtual ICollection<Exchange> ExchangeOriginalSales { get; set; } = new List<Exchange>();

    [InverseProperty("Sale")]
    public virtual ICollection<SalesItem> SalesItems { get; set; } = new List<SalesItem>();

    [InverseProperty("Sale")]
    public virtual ICollection<SalesPayment> SalesPayments { get; set; } = new List<SalesPayment>();

    [InverseProperty("Sale")]
    public virtual ICollection<SalesReturn> SalesReturns { get; set; } = new List<SalesReturn>();

    [ForeignKey("ShiftId")]
    [InverseProperty("SalesHeaders")]
    public virtual CashierShift Shift { get; set; }
}