// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("BranchId", Name = "ix_SalesReturns_BranchId")]
[Index("CustomerId", Name = "ix_SalesReturns_CustomerId")]
[Index("SaleId", Name = "ix_SalesReturns_SaleId")]
public partial class SalesReturn
{
    [Key]
    public int SalesReturnId { get; set; }

    public int? SaleId { get; set; }

    public int BranchId { get; set; }

    [StringLength(255)]
    public string ReturnNo { get; set; }

    [Column(TypeName = "date")]
    public DateTime? ReturnDate { get; set; }

    public int? CustomerId { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal GrossAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal DiscountAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal TaxAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal RoundOffAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal NetAmount { get; set; }

    public int? RefundModeId { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal ReturnAmount { get; set; }

    [StringLength(255)]
    public string Remarks { get; set; }

    public DateTime CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("SalesReturns")]
    public virtual Branch Branch { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("SalesReturns")]
    public virtual Customer Customer { get; set; }

    [InverseProperty("Return")]
    public virtual ICollection<Exchange> Exchanges { get; set; } = new List<Exchange>();

    [ForeignKey("RefundModeId")]
    [InverseProperty("SalesReturns")]
    public virtual PaymentMode RefundMode { get; set; }

    [ForeignKey("SaleId")]
    [InverseProperty("SalesReturns")]
    public virtual SalesHeader Sale { get; set; }

    [InverseProperty("SalesReturn")]
    public virtual ICollection<SalesReturnItem> SalesReturnItems { get; set; } = new List<SalesReturnItem>();
}