// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Table("SchemeMaster")]
[Index("BranchId", Name = "ix_SchemeMaster_BranchId")]
[Index("BuyItemId", Name = "ix_SchemeMaster_BuyItemId")]
[Index("FreeItemId", Name = "ix_SchemeMaster_FreeItemId")]
public partial class SchemeMaster
{
    [Key]
    public int SchemeId { get; set; }

    public int? BranchId { get; set; }

    [StringLength(255)]
    public string SchemeCode { get; set; }

    [StringLength(100)]
    public string SchemeType { get; set; }

    [Column(TypeName = "date")]
    public DateTime? EffectiveDate { get; set; }

    public int? BuyItemId { get; set; }

    [StringLength(255)]
    public string BuyBarcode { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal BuyQty { get; set; }

    public int? FreeItemId { get; set; }

    [StringLength(255)]
    public string FreeBarcode { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal FreeQty { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal DiscountPct { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("SchemeMasters")]
    public virtual Branch Branch { get; set; }

    [ForeignKey("BuyItemId")]
    [InverseProperty("SchemeMasterBuyItems")]
    public virtual Item BuyItem { get; set; }

    [ForeignKey("FreeItemId")]
    [InverseProperty("SchemeMasterFreeItems")]
    public virtual Item FreeItem { get; set; }
}