// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("SizeGroup", "SizeName", Name = "uq_Sizes_GroupName", IsUnique = true)]
public partial class Size
{
    [Key]
    public int SizeId { get; set; }

    [StringLength(50)]
    public string SizeCode { get; set; }

    [Required]
    [StringLength(255)]
    public string SizeName { get; set; }

    [StringLength(100)]
    public string SizeGroup { get; set; }

    public int DisplayOrder { get; set; }

    public bool IsActive { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [InverseProperty("Size")]
    public virtual ICollection<ItemVariant> ItemVariants { get; set; } = new List<ItemVariant>();
}