// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("ApprovedBy", Name = "ix_StockAdjustments_ApprovedBy")]
[Index("BranchId", Name = "ix_StockAdjustments_BranchId")]
public partial class StockAdjustment
{
    [Key]
    public int StockAdjustmentId { get; set; }

    public int BranchId { get; set; }

    [StringLength(255)]
    public string AdjustmentNo { get; set; }

    [Column(TypeName = "date")]
    public DateTime? AdjustmentDate { get; set; }

    [StringLength(100)]
    public string AdjustmentType { get; set; }

    [StringLength(255)]
    public string Reason { get; set; }

    public int? TotalItems { get; set; }

    [StringLength(255)]
    public string Remarks { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    public DateTime? ApprovedOn { get; set; }

    public int? ApprovedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("ApprovedBy")]
    [InverseProperty("StockAdjustments")]
    public virtual User ApprovedByNavigation { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("StockAdjustments")]
    public virtual Branch Branch { get; set; }

    [InverseProperty("StockAdjustment")]
    public virtual ICollection<StockAdjustmentItem> StockAdjustmentItems { get; set; } = new List<StockAdjustmentItem>();
}