// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("ItemId", Name = "ix_StockTransferItems_ItemId")]
[Index("StockTransferId", Name = "ix_StockTransferItems_TransferId")]
public partial class StockTransferItem
{
    [Key]
    public int StockTransferItemId { get; set; }

    public int StockTransferId { get; set; }

    public int ItemId { get; set; }

    public int? ItemVariantId { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal Qty { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal Rate { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal ValueAmount { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("ItemId")]
    [InverseProperty("StockTransferItems")]
    public virtual Item Item { get; set; }

    [ForeignKey("ItemVariantId")]
    [InverseProperty("StockTransferItems")]
    public virtual ItemVariant ItemVariant { get; set; }

    [ForeignKey("StockTransferId")]
    [InverseProperty("StockTransferItems")]
    public virtual StockTransfer StockTransfer { get; set; }
}