// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("StockAdjustmentId", Name = "ix_StockAdjustmentItems_AdjustmentId")]
[Index("ItemId", Name = "ix_StockAdjustmentItems_ItemId")]
[Index("ItemVariantId", Name = "ix_StockAdjustmentItems_ItemVariantId")]
public partial class StockAdjustmentItem
{
    [Key]
    public int StockAdjustmentItemId { get; set; }

    public int StockAdjustmentId { get; set; }

    public int ItemId { get; set; }

    public int? ItemVariantId { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? SystemQty { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? PhysicalQty { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? DifferenceQty { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal ExcessQty { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal ShortageQty { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? Rate { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? ValueAmount { get; set; }

    [StringLength(255)]
    public string Remarks { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("ItemId")]
    [InverseProperty("StockAdjustmentItems")]
    public virtual Item Item { get; set; }

    [ForeignKey("ItemVariantId")]
    [InverseProperty("StockAdjustmentItems")]
    public virtual ItemVariant ItemVariant { get; set; }

    [ForeignKey("StockAdjustmentId")]
    [InverseProperty("StockAdjustmentItems")]
    public virtual StockAdjustment StockAdjustment { get; set; }
}