// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("FromBranchId", Name = "ix_StockTransfers_FromBranchId")]
[Index("ToBranchId", Name = "ix_StockTransfers_ToBranchId")]
public partial class StockTransfer
{
    [Key]
    public int StockTransferId { get; set; }

    public int FromBranchId { get; set; }

    public int ToBranchId { get; set; }

    [StringLength(255)]
    public string TransferNo { get; set; }

    [Column(TypeName = "date")]
    public DateTime? TransferDate { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    [StringLength(255)]
    public string Remarks { get; set; }

    public DateTime? ApprovedOn { get; set; }

    public int? ApprovedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("ApprovedBy")]
    [InverseProperty("StockTransfers")]
    public virtual User ApprovedByNavigation { get; set; }

    [ForeignKey("FromBranchId")]
    [InverseProperty("StockTransferFromBranches")]
    public virtual Branch FromBranch { get; set; }

    [InverseProperty("StockTransfer")]
    public virtual ICollection<StockTransferItem> StockTransferItems { get; set; } = new List<StockTransferItem>();

    [ForeignKey("ToBranchId")]
    [InverseProperty("StockTransferToBranches")]
    public virtual Branch ToBranch { get; set; }
}