// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Table("StockLedger")]
[Index("BranchId", Name = "ix_StockLedger_BranchId")]
[Index("ItemId", "BranchId", Name = "ix_StockLedger_ItemBranch")]
[Index("ItemId", Name = "ix_StockLedger_ItemId")]
[Index("ItemVariantId", Name = "ix_StockLedger_ItemVariantId")]
[Index("TxnDate", Name = "ix_StockLedger_TxnDate")]
public partial class StockLedger
{
    [Key]
    public int StockLedgerId { get; set; }

    public int BranchId { get; set; }

    public int ItemId { get; set; }

    public int? ItemVariantId { get; set; }

    [StringLength(100)]
    public string ReferenceType { get; set; }

    public int? ReferenceId { get; set; }

    public DateTime? TxnDate { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal InQty { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal OutQty { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? BalanceQty { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal Rate { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal ValueAmount { get; set; }

    [StringLength(255)]
    public string Narration { get; set; }

    public DateTime CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("StockLedgers")]
    public virtual Branch Branch { get; set; }

    [ForeignKey("ItemId")]
    [InverseProperty("StockLedgers")]
    public virtual Item Item { get; set; }

    [ForeignKey("ItemVariantId")]
    [InverseProperty("StockLedgers")]
    public virtual ItemVariant ItemVariant { get; set; }
}