// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("CategoryId", Name = "ix_SubCategories_CategoryId")]
[Index("CategoryId", "SubCategoryCode", Name = "uq_SubCategories_CategorySubCategoryCode", IsUnique = true)]
public partial class SubCategory
{
    [Key]
    public int SubCategoryId { get; set; }

    public int? CategoryId { get; set; }

    [StringLength(255)]
    public string SubCategoryCode { get; set; }

    [StringLength(255)]
    public string SubCategoryName { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    public int DisplayOrder { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("SubCategories")]
    public virtual Category Category { get; set; }

    [InverseProperty("SubCategory")]
    public virtual ICollection<Item> Items { get; set; } = new List<Item>();
}