// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("SupplierCode", Name = "uq_Suppliers_SupplierCode", IsUnique = true)]
public partial class Supplier
{
    [Key]
    public int SupplierId { get; set; }

    [StringLength(255)]
    public string SupplierCode { get; set; }

    [StringLength(255)]
    public string SupplierName { get; set; }

    [StringLength(255)]
    public string ShortName { get; set; }

    [StringLength(255)]
    public string PrintName { get; set; }

    [StringLength(255)]
    public string ContactPerson { get; set; }

    [StringLength(255)]
    public string MobileNumber { get; set; }

    [StringLength(255)]
    public string PhoneNumber { get; set; }

    [StringLength(255)]
    public string Email { get; set; }

    [StringLength(255)]
    public string Website { get; set; }

    [StringLength(255)]
    public string Address1 { get; set; }

    [StringLength(255)]
    public string Address2 { get; set; }

    [StringLength(255)]
    public string Address3 { get; set; }

    [StringLength(255)]
    public string City { get; set; }

    [StringLength(255)]
    public string State { get; set; }

    [StringLength(255)]
    public string Country { get; set; }

    [StringLength(255)]
    public string Pincode { get; set; }

    [StringLength(255)]
    public string Gstin { get; set; }

    [StringLength(255)]
    public string Pan { get; set; }

    [StringLength(255)]
    public string TinNo { get; set; }

    [StringLength(255)]
    public string CstNo { get; set; }

    [StringLength(255)]
    public string PaymentTerms { get; set; }

    public int CreditDays { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal OpeningBalance { get; set; }

    [StringLength(10)]
    public string OpeningBalType { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    [StringLength(255)]
    public string LegalCompanyName { get; set; }

    [StringLength(255)]
    public string WhatsappNumber { get; set; }

    [StringLength(255)]
    public string RegistrationType { get; set; }

    [Column("MSME")]
    [StringLength(255)]
    public string Msme { get; set; }

    [StringLength(255)]
    public string DefaultTaxRate { get; set; }

    [Column("TDSApplicable")]
    [StringLength(255)]
    public string Tdsapplicable { get; set; }

    [StringLength(255)]
    public string Currency { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? MinOrderValue { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? DefaultDiscount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? CreditLimit { get; set; }

    [StringLength(255)]
    public string PriorityTier { get; set; }

    public int? CategoryId { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("Suppliers")]
    public virtual Category Category { get; set; }

    [InverseProperty("Supplier")]
    public virtual ICollection<ItemSupplier> ItemSuppliers { get; set; } = new List<ItemSupplier>();

    [InverseProperty("Supplier")]
    public virtual ICollection<PurchaseHeader> PurchaseHeaders { get; set; } = new List<PurchaseHeader>();

    [InverseProperty("Supplier")]
    public virtual ICollection<PurchaseReturn> PurchaseReturns { get; set; } = new List<PurchaseReturn>();

    [InverseProperty("Supplier")]
    public virtual ICollection<SupplierAccount> SupplierAccounts { get; set; } = new List<SupplierAccount>();

    [InverseProperty("Supplier")]
    public virtual ICollection<SupplierLedger> SupplierLedgers { get; set; } = new List<SupplierLedger>();
}