// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Table("SupplierLedger")]
[Index("SupplierId", Name = "ix_SupplierLedger_SupplierId")]
public partial class SupplierLedger
{
    [Key]
    public int SupplierLedgerId { get; set; }

    public int SupplierId { get; set; }

    [StringLength(100)]
    public string ReferenceType { get; set; }

    public int? ReferenceId { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal DebitAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal CreditAmount { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? BalanceAfterTxn { get; set; }

    public DateTime? TxnDate { get; set; }

    [StringLength(500)]
    public string Narration { get; set; }

    public DateTime CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("SupplierId")]
    [InverseProperty("SupplierLedgers")]
    public virtual Supplier Supplier { get; set; }
}