// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

public partial class SupplierAccount
{
    [Key]
    public int SupplierAccountId { get; set; }

    [Required]
    [StringLength(255)]
    public string AccountHolderName { get; set; }

    [Required]
    [StringLength(255)]
    public string AccountNumber { get; set; }

    [Required]
    [StringLength(255)]
    public string BankName { get; set; }

    [Required]
    [StringLength(255)]
    public string BranchCode { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedOn { get; set; }

    public bool IsActive { get; set; }

    public int? SupplierId { get; set; }


    [ForeignKey("SupplierId")]
    [InverseProperty("SupplierAccounts")]
    public virtual Supplier Supplier { get; set; }
}