// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("TaxCode", Name = "uq_TaxMasters_TaxCode", IsUnique = true)]
public partial class TaxMaster
{
    [Key]
    public int TaxId { get; set; }

    [StringLength(255)]
    public string TaxCode { get; set; }

    [StringLength(255)]
    public string TaxName { get; set; }

    [StringLength(100)]
    public string TaxType { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal CgstRate { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal SgstRate { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal IgstRate { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal CessRate { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal TotalTaxRate { get; set; }

    public bool IsInclusive { get; set; }

    [StringLength(255)]
    public string HsnCode { get; set; }

    [Column(TypeName = "date")]
    public DateTime? EffectiveFrom { get; set; }

    [Column(TypeName = "date")]
    public DateTime? EffectiveTo { get; set; }

    public bool IsActive { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [InverseProperty("Tax")]
    public virtual ICollection<HeldBillItem> HeldBillItems { get; set; } = new List<HeldBillItem>();

    [InverseProperty("PurchaseTax")]
    public virtual ICollection<Item> ItemPurchaseTaxes { get; set; } = new List<Item>();

    [InverseProperty("SalesTax")]
    public virtual ICollection<Item> ItemSalesTaxes { get; set; } = new List<Item>();

    [InverseProperty("Tax")]
    public virtual ICollection<PurchaseAdditionalCharge> PurchaseAdditionalCharges { get; set; } = new List<PurchaseAdditionalCharge>();

    [InverseProperty("Tax")]
    public virtual ICollection<PurchaseItem> PurchaseItems { get; set; } = new List<PurchaseItem>();

    [InverseProperty("Tax")]
    public virtual ICollection<SalesItem> SalesItems { get; set; } = new List<SalesItem>();
}