// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("UnitCode", Name = "uq_Units_UnitCode", IsUnique = true)]
public partial class Unit
{
    [Key]
    public int UnitId { get; set; }

    [StringLength(50)]
    public string UnitCode { get; set; }

    [StringLength(255)]
    public string UnitName { get; set; }

    [StringLength(50)]
    public string UnitShortName { get; set; }

    public bool DecimalAllowed { get; set; }

    [StringLength(50)]
    public string GstUnitCode { get; set; }

    public bool IsActive { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [InverseProperty("Unit")]
    public virtual ICollection<Item> Items { get; set; } = new List<Item>();
}