// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("BranchId", Name = "ix_Users_BranchId")]
[Index("RoleId", Name = "ix_Users_RoleId")]
[Index("LoginName", Name = "uq_Users_LoginName", IsUnique = true)]
[Index("UserCode", Name = "uq_Users_UserCode", IsUnique = true)]
public partial class User
{
    [Key]
    public int UserId { get; set; }

    public int? BranchId { get; set; }

    public int? RoleId { get; set; }

    [StringLength(255)]
    public string UserCode { get; set; }

    [StringLength(255)]
    public string FullName { get; set; }

    [StringLength(255)]
    public string MobileNumber { get; set; }

    [StringLength(255)]
    public string Email { get; set; }

    [StringLength(255)]
    public string LoginName { get; set; }

    [StringLength(255)]
    public string PasswordHash { get; set; }

    [StringLength(50)]
    public string PinCode { get; set; }

    [StringLength(255)]
    public string DefaultScreen { get; set; }

    public bool IsActive { get; set; }

    public DateTime? LastLoginAt { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [InverseProperty("UpdatedByNavigation")]
    public virtual ICollection<AppSetting> AppSettings { get; set; } = new List<AppSetting>();

    [InverseProperty("AppliedByNavigation")]
    public virtual ICollection<AppliedOffersLog> AppliedOffersLogs { get; set; } = new List<AppliedOffersLog>();

    [InverseProperty("PerformedByNavigation")]
    public virtual ICollection<AuditLog> AuditLogs { get; set; } = new List<AuditLog>();

    [InverseProperty("PrintedByNavigation")]
    public virtual ICollection<BarcodePrintBatch> BarcodePrintBatches { get; set; } = new List<BarcodePrintBatch>();

    [ForeignKey("BranchId")]
    [InverseProperty("Users")]
    public virtual Branch Branch { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<CashierShift> CashierShifts { get; set; } = new List<CashierShift>();

    [InverseProperty("AssignedUser")]
    public virtual ICollection<Device> Devices { get; set; } = new List<Device>();

    [InverseProperty("HeldByNavigation")]
    public virtual ICollection<HeldBill> HeldBills { get; set; } = new List<HeldBill>();

    [InverseProperty("ChangedByNavigation")]
    public virtual ICollection<ItemPriceHistory> ItemPriceHistories { get; set; } = new List<ItemPriceHistory>();

    [ForeignKey("RoleId")]
    [InverseProperty("Users")]
    public virtual Role Role { get; set; }

    [InverseProperty("ApprovedByNavigation")]
    public virtual ICollection<StockAdjustment> StockAdjustments { get; set; } = new List<StockAdjustment>();

    [InverseProperty("ApprovedByNavigation")]
    public virtual ICollection<StockTransfer> StockTransfers { get; set; } = new List<StockTransfer>();

    [InverseProperty("User")]
    public virtual ICollection<UserSession> UserSessions { get; set; } = new List<UserSession>();
}