// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartWorkerAutomation.Core.Models;

[Index("UserId", Name = "ix_UserSessions_UserId")]
public partial class UserSession
{
    [Key]
    public int SessionId { get; set; }

    public int UserId { get; set; }

    public int? DeviceId { get; set; }

    public DateTime LoginAt { get; set; }

    public DateTime? LogoutAt { get; set; }

    [StringLength(255)]
    public string IpAddress { get; set; }

    [StringLength(255)]
    public string DeviceInfo { get; set; }

    public bool IsActive { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("DeviceId")]
    [InverseProperty("UserSessions")]
    public virtual Device Device { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserSessions")]
    public virtual User User { get; set; }
}