// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using SmartWorkerAutomation.Core.Models;

namespace SmartWorkerAutomation.Core.DBContext;

public partial class SmartWorkerAutomationContext : DbContext
{
    public SmartWorkerAutomationContext(DbContextOptions<SmartWorkerAutomationContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AppSetting> AppSettings { get; set; }

    public virtual DbSet<AppliedOffersLog> AppliedOffersLogs { get; set; }

    public virtual DbSet<Area> Areas { get; set; }

    public virtual DbSet<AuditLog> AuditLogs { get; set; }

    public virtual DbSet<BarcodePrintBatch> BarcodePrintBatches { get; set; }

    public virtual DbSet<BarcodePrintBatchItem> BarcodePrintBatchItems { get; set; }

    public virtual DbSet<Branch> Branches { get; set; }

    public virtual DbSet<Brand> Brands { get; set; }

    public virtual DbSet<CashDenomination> CashDenominations { get; set; }

    public virtual DbSet<CashierShift> CashierShifts { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Colour> Colours { get; set; }

    public virtual DbSet<Company> Companies { get; set; }

    public virtual DbSet<Counter> Counters { get; set; }

    public virtual DbSet<CounterPayout> CounterPayouts { get; set; }

    public virtual DbSet<Coupon> Coupons { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<CustomerLedger> CustomerLedgers { get; set; }

    public virtual DbSet<CustomerLoyaltyTransaction> CustomerLoyaltyTransactions { get; set; }

    public virtual DbSet<DailySalesSummary> DailySalesSummaries { get; set; }

    public virtual DbSet<Device> Devices { get; set; }

    public virtual DbSet<Document> Documents { get; set; }

    public virtual DbSet<Exchange> Exchanges { get; set; }

    public virtual DbSet<HeldBill> HeldBills { get; set; }

    public virtual DbSet<HeldBillItem> HeldBillItems { get; set; }

    public virtual DbSet<Item> Items { get; set; }

    public virtual DbSet<ItemAlternateBarcode> ItemAlternateBarcodes { get; set; }

    public virtual DbSet<ItemPriceHistory> ItemPriceHistories { get; set; }

    public virtual DbSet<ItemSupplier> ItemSuppliers { get; set; }

    public virtual DbSet<ItemVariant> ItemVariants { get; set; }

    public virtual DbSet<Location> Locations { get; set; }

    public virtual DbSet<LoyaltyProgram> LoyaltyPrograms { get; set; }

    public virtual DbSet<Offer> Offers { get; set; }

    public virtual DbSet<OfferCondition> OfferConditions { get; set; }

    public virtual DbSet<OfferItem> OfferItems { get; set; }

    public virtual DbSet<PaymentMode> PaymentModes { get; set; }

    public virtual DbSet<Permission> Permissions { get; set; }

    public virtual DbSet<PurchaseActivityLog> PurchaseActivityLogs { get; set; }

    public virtual DbSet<PurchaseAdditionalCharge> PurchaseAdditionalCharges { get; set; }

    public virtual DbSet<PurchaseHeader> PurchaseHeaders { get; set; }

    public virtual DbSet<PurchaseItem> PurchaseItems { get; set; }

    public virtual DbSet<PurchasePayment> PurchasePayments { get; set; }

    public virtual DbSet<PurchaseReturn> PurchaseReturns { get; set; }

    public virtual DbSet<PurchaseStatus> PurchaseStatuses { get; set; }

    public virtual DbSet<RefreshToken> RefreshTokens { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<RolePermission> RolePermissions { get; set; }

    public virtual DbSet<SalesHeader> SalesHeaders { get; set; }

    public virtual DbSet<SalesItem> SalesItems { get; set; }

    public virtual DbSet<SalesPayment> SalesPayments { get; set; }

    public virtual DbSet<SalesReturn> SalesReturns { get; set; }

    public virtual DbSet<SalesReturnItem> SalesReturnItems { get; set; }

    public virtual DbSet<SchemeMaster> SchemeMasters { get; set; }

    public virtual DbSet<Size> Sizes { get; set; }

    public virtual DbSet<StockAdjustment> StockAdjustments { get; set; }

    public virtual DbSet<StockAdjustmentItem> StockAdjustmentItems { get; set; }

    public virtual DbSet<StockLedger> StockLedgers { get; set; }

    public virtual DbSet<StockTransfer> StockTransfers { get; set; }

    public virtual DbSet<StockTransferItem> StockTransferItems { get; set; }

    public virtual DbSet<SubCategory> SubCategories { get; set; }

    public virtual DbSet<Supplier> Suppliers { get; set; }

    public virtual DbSet<SupplierAccount> SupplierAccounts { get; set; }

    public virtual DbSet<SupplierLedger> SupplierLedgers { get; set; }

    public virtual DbSet<TaxMaster> TaxMasters { get; set; }

    public virtual DbSet<Unit> Units { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserSession> UserSessions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AppSetting>(entity =>
        {
            entity.HasKey(e => e.SettingId).HasName("PK__AppSetti__54372B1DD2E1D4B8");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.UpdatedOn).HasDefaultValueSql("(sysdatetime())");

            entity.HasOne(d => d.Branch).WithMany(p => p.AppSettings).HasConstraintName("FK__AppSettin__Branc__1E05700A");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.AppSettings).HasConstraintName("FK__AppSettin__Updat__20E1DCB5");
        });

        modelBuilder.Entity<AppliedOffersLog>(entity =>
        {
            entity.HasKey(e => e.AppliedOfferLogId).HasName("PK__AppliedO__E5D9A37FC57A7DA8");

            entity.Property(e => e.AppliedOn).HasDefaultValueSql("(sysdatetime())");

            entity.HasOne(d => d.AppliedByNavigation).WithMany(p => p.AppliedOffersLogs).HasConstraintName("FK__AppliedOf__Appli__7E8CC4B1");

            entity.HasOne(d => d.Offer).WithMany(p => p.AppliedOffersLogs).HasConstraintName("FK__AppliedOf__Offer__7BB05806");

            entity.HasOne(d => d.Sale).WithMany(p => p.AppliedOffersLogs)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__AppliedOf__SaleI__79C80F94");

            entity.HasOne(d => d.SaleItem).WithMany(p => p.AppliedOffersLogs).HasConstraintName("FK__AppliedOf__SaleI__7ABC33CD");
        });

        modelBuilder.Entity<Area>(entity =>
        {
            entity.HasKey(e => e.AreaId).HasName("PK__Areas__70B8204887C44935");

            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
        });

        modelBuilder.Entity<AuditLog>(entity =>
        {
            entity.HasKey(e => e.AuditLogId).HasName("PK__AuditLog__EB5F6CBD59E4203B");

            entity.Property(e => e.PerformedOn).HasDefaultValueSql("(sysdatetime())");

            entity.HasOne(d => d.PerformedByNavigation).WithMany(p => p.AuditLogs).HasConstraintName("FK__AuditLogs__Perfo__1B29035F");
        });

        modelBuilder.Entity<BarcodePrintBatch>(entity =>
        {
            entity.HasKey(e => e.BarcodePrintBatchId).HasName("PK__BarcodeP__623AFFBF2D667A24");

            entity.HasOne(d => d.Branch).WithMany(p => p.BarcodePrintBatches)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__BarcodePr__Branc__0169315C");

            entity.HasOne(d => d.PrintedByNavigation).WithMany(p => p.BarcodePrintBatches).HasConstraintName("FK__BarcodePr__Print__025D5595");
        });

        modelBuilder.Entity<BarcodePrintBatchItem>(entity =>
        {
            entity.HasKey(e => e.BarcodePrintBatchItemId).HasName("PK__BarcodeP__8296EDA4335E2781");

            entity.HasOne(d => d.BarcodePrintBatch).WithMany(p => p.BarcodePrintBatchItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__BarcodePr__Barco__0539C240");

            entity.HasOne(d => d.Item).WithMany(p => p.BarcodePrintBatchItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__BarcodePr__ItemI__062DE679");

            entity.HasOne(d => d.ItemVariant).WithMany(p => p.BarcodePrintBatchItems).HasConstraintName("FK__BarcodePr__ItemV__07220AB2");
        });

        modelBuilder.Entity<Branch>(entity =>
        {
            entity.HasKey(e => e.BranchId).HasName("PK__Branches__A1682FC575A55CC9");

            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.UpdatedOn).HasDefaultValueSql("(sysdatetime())");

            entity.HasOne(d => d.Company).WithMany(p => p.Branches)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Branches__Compan__18EBB532");
        });

        modelBuilder.Entity<Brand>(entity =>
        {
            entity.HasKey(e => e.BrandId).HasName("PK__Brands__DAD4F05EBDF49456");

            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.UpdatedOn).HasDefaultValueSql("(sysdatetime())");
        });

        modelBuilder.Entity<CashDenomination>(entity =>
        {
            entity.HasKey(e => e.DenominationId).HasName("PK__CashDeno__22DF18E5993F8A47");

            entity.Property(e => e.EnteredOn).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.EntryType).HasDefaultValue("CLOSING");

            entity.HasOne(d => d.Shift).WithMany(p => p.CashDenominations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CashDenom__Shift__1209AD79");
        });

        modelBuilder.Entity<CashierShift>(entity =>
        {
            entity.HasKey(e => e.ShiftId).HasName("PK__CashierS__C0A838819DEC6F62");

            entity.HasOne(d => d.Branch).WithMany(p => p.CashierShifts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CashierSh__Branc__05A3D694");

            entity.HasOne(d => d.Counter).WithMany(p => p.CashierShifts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CashierSh__Count__0697FACD");

            entity.HasOne(d => d.User).WithMany(p => p.CashierShifts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CashierSh__UserI__078C1F06");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK__Categori__19093A0B30F024EC");

            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.UpdatedOn).HasDefaultValueSql("(sysdatetime())");
        });

        modelBuilder.Entity<Colour>(entity =>
        {
            entity.HasKey(e => e.ColourId).HasName("PK__Colours__4A2D245F2F9F2FDA");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
        });

        modelBuilder.Entity<Company>(entity =>
        {
            entity.HasKey(e => e.CompanyId).HasName("PK__Companie__2D971CAC8B569428");

            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.CurrencyCode).HasDefaultValue("INR");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Timezone).HasDefaultValue("Asia/Kolkata");
            entity.Property(e => e.UpdatedOn).HasDefaultValueSql("(sysdatetime())");
        });

        modelBuilder.Entity<Counter>(entity =>
        {
            entity.HasKey(e => e.CounterId).HasName("PK__Counters__F12879C44CF099FF");

            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.Branch).WithMany(p => p.Counters)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Counters__Branch__7755B73D");
        });

        modelBuilder.Entity<CounterPayout>(entity =>
        {
            entity.HasKey(e => e.PayoutId).HasName("PK__CounterP__35C3DF8E22D5428E");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.PayoutDate).HasDefaultValueSql("(sysdatetime())");

            entity.HasOne(d => d.Branch).WithMany(p => p.CounterPayouts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CounterPa__Branc__2334397B");

            entity.HasOne(d => d.Shift).WithMany(p => p.CounterPayouts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CounterPa__Shift__22401542");
        });

        modelBuilder.Entity<Coupon>(entity =>
        {
            entity.HasKey(e => e.CouponId).HasName("PK__Coupons__384AF1BA9EA4F71A");
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.CustomerId).HasName("PK__Customer__A4AE64D86C29BAEB");

            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.UpdatedOn).HasDefaultValueSql("(sysdatetime())");
        });

        modelBuilder.Entity<CustomerLedger>(entity =>
        {
            entity.HasKey(e => e.CustomerLedgerId).HasName("PK__Customer__3F764B0CC219C6FF");

            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(sysdatetime())");

            entity.HasOne(d => d.Customer).WithMany(p => p.CustomerLedgers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CustomerL__Custo__6991A7CB");
        });

        modelBuilder.Entity<CustomerLoyaltyTransaction>(entity =>
        {
            entity.HasKey(e => e.CustomerLoyaltyTxnId).HasName("PK__Customer__0262D30DA57482CE");

            entity.HasOne(d => d.Customer).WithMany(p => p.CustomerLoyaltyTransactions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CustomerL__Custo__75035A77");
        });

        modelBuilder.Entity<DailySalesSummary>(entity =>
        {
            entity.HasKey(e => e.DailySalesSummaryId).HasName("PK__DailySal__0D5EA73AB1E7B575");

            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(sysdatetime())");

            entity.HasOne(d => d.Branch).WithMany(p => p.DailySalesSummaries)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DailySale__Branc__0AF29B96");
        });

        modelBuilder.Entity<Device>(entity =>
        {
            entity.HasKey(e => e.DeviceId).HasName("PK__Devices__49E1231144E5C9C7");

            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.AssignedUser).WithMany(p => p.Devices).HasConstraintName("FK__Devices__Assigne__7C1A6C5A");

            entity.HasOne(d => d.Branch).WithMany(p => p.Devices)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Devices__BranchI__7B264821");
        });

        modelBuilder.Entity<Document>(entity =>
        {
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.UpdatedOn).HasDefaultValueSql("(sysdatetime())");
        });

        modelBuilder.Entity<Exchange>(entity =>
        {
            entity.HasKey(e => e.ExchangeId).HasName("PK__Exchange__72E6008B4BE8D67B");

            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(sysdatetime())");

            entity.HasOne(d => d.NewSale).WithMany(p => p.ExchangeNewSales).HasConstraintName("FK__Exchanges__NewSa__64CCF2AE");

            entity.HasOne(d => d.OriginalSale).WithMany(p => p.ExchangeOriginalSales).HasConstraintName("FK__Exchanges__Origi__62E4AA3C");

            entity.HasOne(d => d.Return).WithMany(p => p.Exchanges).HasConstraintName("FK__Exchanges__Retur__63D8CE75");
        });

        modelBuilder.Entity<HeldBill>(entity =>
        {
            entity.HasKey(e => e.HeldBillId).HasName("PK__HeldBill__AD43664BBD7C2009");

            entity.HasOne(d => d.Branch).WithMany(p => p.HeldBills)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__HeldBills__Branc__7BE56230");

            entity.HasOne(d => d.Counter).WithMany(p => p.HeldBills)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__HeldBills__Count__7CD98669");

            entity.HasOne(d => d.Customer).WithMany(p => p.HeldBills).HasConstraintName("FK__HeldBills__Custo__7DCDAAA2");

            entity.HasOne(d => d.HeldByNavigation).WithMany(p => p.HeldBills).HasConstraintName("FK__HeldBills__HeldB__7EC1CEDB");
        });

        modelBuilder.Entity<HeldBillItem>(entity =>
        {
            entity.HasKey(e => e.HeldBillItemId).HasName("PK__HeldBill__AB9DBB387A656E75");

            entity.HasOne(d => d.HeldBill).WithMany(p => p.HeldBillItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__HeldBillI__HeldB__019E3B86");

            entity.HasOne(d => d.Item).WithMany(p => p.HeldBillItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__HeldBillI__ItemI__02925FBF");

            entity.HasOne(d => d.ItemVariant).WithMany(p => p.HeldBillItems).HasConstraintName("FK__HeldBillI__ItemV__038683F8");

            entity.HasOne(d => d.Tax).WithMany(p => p.HeldBillItems).HasConstraintName("FK__HeldBillI__TaxId__084B3915");
        });

        modelBuilder.Entity<Item>(entity =>
        {
            entity.HasKey(e => e.ItemId).HasName("PK__Items__727E838BFA0EF5D1");

            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.HasVariants).HasDefaultValue(true);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.IsStockTracked).HasDefaultValue(true);
            entity.Property(e => e.ItemType).HasDefaultValue("Product");
            entity.Property(e => e.PackingSize).HasDefaultValue(1m);
            entity.Property(e => e.UpdatedOn).HasDefaultValueSql("(sysdatetime())");

            entity.HasOne(d => d.Branch).WithMany(p => p.Items).HasConstraintName("FK__Items__BranchId__2645B050");

            entity.HasOne(d => d.Brand).WithMany(p => p.Items).HasConstraintName("FK__Items__BrandId__29221CFB");

            entity.HasOne(d => d.Category).WithMany(p => p.Items).HasConstraintName("FK__Items__CategoryI__2739D489");

            entity.HasOne(d => d.PurchaseTax).WithMany(p => p.ItemPurchaseTaxes).HasConstraintName("FK__Items__PurchaseT__2BFE89A6");

            entity.HasOne(d => d.SalesTax).WithMany(p => p.ItemSalesTaxes).HasConstraintName("FK__Items__SalesTaxI__2B0A656D");

            entity.HasOne(d => d.SubCategory).WithMany(p => p.Items).HasConstraintName("FK__Items__SubCatego__282DF8C2");

            entity.HasOne(d => d.Unit).WithMany(p => p.Items).HasConstraintName("FK__Items__UnitId__2A164134");
        });

        modelBuilder.Entity<ItemAlternateBarcode>(entity =>
        {
            entity.HasKey(e => e.ItemAlternateBarcodeId).HasName("PK__ItemAlte__90F3900AB516E68C");

            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.Item).WithMany(p => p.ItemAlternateBarcodes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ItemAlter__ItemI__4F47C5E3");

            entity.HasOne(d => d.ItemVariant).WithMany(p => p.ItemAlternateBarcodes).HasConstraintName("FK__ItemAlter__ItemV__503BEA1C");
        });

        modelBuilder.Entity<ItemPriceHistory>(entity =>
        {
            entity.HasKey(e => e.ItemPriceHistoryId).HasName("PK__ItemPric__7FCDF11504370DF3");

            entity.Property(e => e.ChangedOn).HasDefaultValueSql("(sysdatetime())");

            entity.HasOne(d => d.ChangedByNavigation).WithMany(p => p.ItemPriceHistories).HasConstraintName("FK__ItemPrice__Chang__607251E5");

            entity.HasOne(d => d.Item).WithMany(p => p.ItemPriceHistories)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ItemPrice__ItemI__5D95E53A");

            entity.HasOne(d => d.ItemVariant).WithMany(p => p.ItemPriceHistories).HasConstraintName("FK__ItemPrice__ItemV__5E8A0973");
        });

        modelBuilder.Entity<ItemSupplier>(entity =>
        {
            entity.HasKey(e => e.ItemSupplierId).HasName("PK__ItemSupp__524AAC0772C0A741");

            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.Item).WithMany(p => p.ItemSuppliers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ItemSuppl__ItemI__55F4C372");

            entity.HasOne(d => d.Supplier).WithMany(p => p.ItemSuppliers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ItemSuppl__Suppl__56E8E7AB");
        });

        modelBuilder.Entity<ItemVariant>(entity =>
        {
            entity.HasKey(e => e.ItemVariantId).HasName("PK__ItemVari__5DBBD1A9EEADB2B2");

            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.UpdatedOn).HasDefaultValueSql("(sysdatetime())");

            entity.HasOne(d => d.Colour).WithMany(p => p.ItemVariants).HasConstraintName("FK__ItemVaria__Colou__47A6A41B");

            entity.HasOne(d => d.Item).WithMany(p => p.ItemVariants)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ItemVaria__ItemI__46B27FE2");

            entity.HasOne(d => d.Size).WithMany(p => p.ItemVariants).HasConstraintName("FK__ItemVaria__SizeI__489AC854");
        });

        modelBuilder.Entity<LoyaltyProgram>(entity =>
        {
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(sysdatetime())");
        });

        modelBuilder.Entity<Offer>(entity =>
        {
            entity.HasKey(e => e.OfferId).HasName("PK__Offers__8EBCF091EC800AEB");

            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.UpdatedOn).HasDefaultValueSql("(sysdatetime())");
        });

        modelBuilder.Entity<OfferCondition>(entity =>
        {
            entity.HasKey(e => e.OfferConditionId).HasName("PK__OfferCon__868D3D3CAE6596C1");

            entity.HasOne(d => d.FreeItem).WithMany(p => p.OfferConditions).HasConstraintName("FK__OfferCond__FreeI__6442E2C9");

            entity.HasOne(d => d.Offer).WithMany(p => p.OfferConditions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OfferCond__Offer__634EBE90");
        });

        modelBuilder.Entity<OfferItem>(entity =>
        {
            entity.HasKey(e => e.OfferItemId).HasName("PK__OfferIte__51A478ADFCDB7A8B");

            entity.HasOne(d => d.Brand).WithMany(p => p.OfferItems).HasConstraintName("FK__OfferItem__Brand__6AEFE058");

            entity.HasOne(d => d.Category).WithMany(p => p.OfferItems).HasConstraintName("FK__OfferItem__Categ__69FBBC1F");

            entity.HasOne(d => d.Item).WithMany(p => p.OfferItems).HasConstraintName("FK__OfferItem__ItemI__690797E6");

            entity.HasOne(d => d.Offer).WithMany(p => p.OfferItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OfferItem__Offer__681373AD");
        });

        modelBuilder.Entity<PaymentMode>(entity =>
        {
            entity.HasKey(e => e.PaymentModeId).HasName("PK__PaymentM__F95995492194CEED");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
        });

        modelBuilder.Entity<Permission>(entity =>
        {
            entity.HasKey(e => e.PermissionId).HasName("PK__Permissi__EFA6FB2F94F76AC6");
        });

        modelBuilder.Entity<PurchaseActivityLog>(entity =>
        {
            entity.HasKey(e => e.LogId).HasName("PK__Purchase__5E54864837C24738");

            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Purchase).WithMany(p => p.PurchaseActivityLogs).HasConstraintName("FK_PurchaseActivityLogs_PurchaseHeaders");
        });

        modelBuilder.Entity<PurchaseAdditionalCharge>(entity =>
        {
            entity.HasOne(d => d.Purchase).WithMany(p => p.PurchaseAdditionalCharges)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchaseAdditionalCharges_PurchaseHeaders");

            entity.HasOne(d => d.Tax).WithMany(p => p.PurchaseAdditionalCharges).HasConstraintName("FK_PurchaseAdditionalCharges_TaxMasters");
        });

        modelBuilder.Entity<PurchaseHeader>(entity =>
        {
            entity.HasKey(e => e.PurchaseId).HasName("PK__Purchase__6B0A6BBE014A7760");

            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.GrnType).HasDefaultValue("Purchase");
            entity.Property(e => e.UpdatedOn).HasDefaultValueSql("(sysdatetime())");

            entity.HasOne(d => d.Branch).WithMany(p => p.PurchaseHeaders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PurchaseH__Branc__28ED12D1");

            entity.HasOne(d => d.Location).WithMany(p => p.PurchaseHeaders).HasConstraintName("FK_PurchaseHeaders_Location");

            entity.HasOne(d => d.PaymentMode).WithMany(p => p.PurchaseHeaders).HasConstraintName("FK__PurchaseH__Payme__39237A9A");

            entity.HasOne(d => d.PurchaseStatus).WithMany(p => p.PurchaseHeaders).HasConstraintName("FK_PurchaseHeaders_PurChaseStatus");

            entity.HasOne(d => d.Supplier).WithMany(p => p.PurchaseHeaders).HasConstraintName("FK__PurchaseH__Suppl__29E1370A");
        });

        modelBuilder.Entity<PurchaseItem>(entity =>
        {
            entity.HasKey(e => e.PurchaseItemId).HasName("PK__Purchase__B48BB687F5D9A880");

            entity.Property(e => e.PackingSize).HasDefaultValue(1m);

            entity.HasOne(d => d.Item).WithMany(p => p.PurchaseItems).HasConstraintName("FK__PurchaseI__ItemI__3EDC53F0");

            entity.HasOne(d => d.ItemVariant).WithMany(p => p.PurchaseItems).HasConstraintName("FK__PurchaseI__ItemV__3FD07829");

            entity.HasOne(d => d.Purchase).WithMany(p => p.PurchaseItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PurchaseI__Purch__3DE82FB7");

            entity.HasOne(d => d.Tax).WithMany(p => p.PurchaseItems).HasConstraintName("FK__PurchaseI__TaxId__4C364F0E");
        });

        modelBuilder.Entity<PurchasePayment>(entity =>
        {
            entity.HasKey(e => e.PurchasePaymentId).HasName("PK__Purchase__16D46374751E112B");

            entity.HasOne(d => d.PaymentMode).WithMany(p => p.PurchasePayments).HasConstraintName("FK__PurchaseP__Payme__56B3DD81");

            entity.HasOne(d => d.Purchase).WithMany(p => p.PurchasePayments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PurchaseP__Purch__54CB950F");
        });

        modelBuilder.Entity<RefreshToken>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RefreshT__3214EC07696518DB");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Roles__8AFACE1ACD8DE074");

            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.UpdatedOn).HasDefaultValueSql("(sysdatetime())");
        });

        modelBuilder.Entity<RolePermission>(entity =>
        {
            entity.HasKey(e => e.RolePermissionId).HasName("PK__RolePerm__120F46BA3FCDD7B3");

            entity.HasOne(d => d.Permission).WithMany(p => p.RolePermissions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__RolePermi__Permi__114A936A");

            entity.HasOne(d => d.Role).WithMany(p => p.RolePermissions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__RolePermi__RoleI__10566F31");
        });

        modelBuilder.Entity<SalesHeader>(entity =>
        {
            entity.HasKey(e => e.SaleId).HasName("PK__SalesHea__1EE3C3FF57520F1E");

            entity.Property(e => e.BillType).HasDefaultValue("Sales");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.UpdatedOn).HasDefaultValueSql("(sysdatetime())");

            entity.HasOne(d => d.Branch).WithMany(p => p.SalesHeaders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__SalesHead__Branc__0D0FEE32");

            entity.HasOne(d => d.Counter).WithMany(p => p.SalesHeaders).HasConstraintName("FK__SalesHead__Count__0E04126B");

            entity.HasOne(d => d.Customer).WithMany(p => p.SalesHeaders).HasConstraintName("FK__SalesHead__Custo__10E07F16");

            entity.HasOne(d => d.Shift).WithMany(p => p.SalesHeaders).HasConstraintName("FK__SalesHead__Shift__0EF836A4");
        });

        modelBuilder.Entity<SalesItem>(entity =>
        {
            entity.HasKey(e => e.SaleItemId).HasName("PK__SalesIte__C6059401C1DAB6A4");

            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(sysdatetime())");

            entity.HasOne(d => d.FreeItem).WithMany(p => p.SalesItemFreeItems).HasConstraintName("FK__SalesItem__FreeI__370627FE");

            entity.HasOne(d => d.Item).WithMany(p => p.SalesItemItems).HasConstraintName("FK__SalesItem__ItemI__29AC2CE0");

            entity.HasOne(d => d.ItemVariant).WithMany(p => p.SalesItems).HasConstraintName("FK__SalesItem__ItemV__2AA05119");

            entity.HasOne(d => d.Offer).WithMany(p => p.SalesItems).HasConstraintName("FK__SalesItem__Offer__3429BB53");

            entity.HasOne(d => d.Sale).WithMany(p => p.SalesItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__SalesItem__SaleI__28B808A7");

            entity.HasOne(d => d.Tax).WithMany(p => p.SalesItems).HasConstraintName("FK__SalesItem__TaxId__38EE7070");
        });

        modelBuilder.Entity<SalesPayment>(entity =>
        {
            entity.HasKey(e => e.SalePaymentId).HasName("PK__SalesPay__C5E7A545DD4F3344");

            entity.HasOne(d => d.PaymentMode).WithMany(p => p.SalesPayments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__SalesPaym__Payme__46486B8E");

            entity.HasOne(d => d.Sale).WithMany(p => p.SalesPayments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__SalesPaym__SaleI__45544755");
        });

        modelBuilder.Entity<SalesReturn>(entity =>
        {
            entity.HasKey(e => e.SalesReturnId).HasName("PK__SalesRet__E0906C38298AAA05");

            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(sysdatetime())");

            entity.HasOne(d => d.Branch).WithMany(p => p.SalesReturns)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__SalesRetu__Branc__4CF5691D");

            entity.HasOne(d => d.Customer).WithMany(p => p.SalesReturns).HasConstraintName("FK__SalesRetu__Custo__4DE98D56");

            entity.HasOne(d => d.RefundMode).WithMany(p => p.SalesReturns).HasConstraintName("FK__SalesRetu__Refun__53A266AC");

            entity.HasOne(d => d.Sale).WithMany(p => p.SalesReturns).HasConstraintName("FK__SalesRetu__SaleI__4C0144E4");
        });

        modelBuilder.Entity<SalesReturnItem>(entity =>
        {
            entity.HasKey(e => e.SalesReturnItemId).HasName("PK__SalesRet__A58E1C94F9CFC342");

            entity.HasOne(d => d.Item).WithMany(p => p.SalesReturnItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__SalesRetu__ItemI__5A4F643B");

            entity.HasOne(d => d.ItemVariant).WithMany(p => p.SalesReturnItems).HasConstraintName("FK__SalesRetu__ItemV__5B438874");

            entity.HasOne(d => d.SaleItem).WithMany(p => p.SalesReturnItems).HasConstraintName("FK__SalesRetu__SaleI__595B4002");

            entity.HasOne(d => d.SalesReturn).WithMany(p => p.SalesReturnItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__SalesRetu__Sales__58671BC9");
        });

        modelBuilder.Entity<SchemeMaster>(entity =>
        {
            entity.HasKey(e => e.SchemeId).HasName("PK__SchemeMa__DB7E1A626503A4B8");

            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.Branch).WithMany(p => p.SchemeMasters).HasConstraintName("FK__SchemeMas__Branc__6DCC4D03");

            entity.HasOne(d => d.BuyItem).WithMany(p => p.SchemeMasterBuyItems).HasConstraintName("FK__SchemeMas__BuyIt__6EC0713C");

            entity.HasOne(d => d.FreeItem).WithMany(p => p.SchemeMasterFreeItems).HasConstraintName("FK__SchemeMas__FreeI__70A8B9AE");
        });

        modelBuilder.Entity<Size>(entity =>
        {
            entity.HasKey(e => e.SizeId).HasName("PK__Sizes__83BD097AFE4E0D95");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
        });

        modelBuilder.Entity<StockAdjustment>(entity =>
        {
            entity.HasKey(e => e.StockAdjustmentId).HasName("PK__StockAdj__0A9711B31B0D7F4E");

            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(sysdatetime())");

            entity.HasOne(d => d.ApprovedByNavigation).WithMany(p => p.StockAdjustments).HasConstraintName("FK__StockAdju__Appro__640DD89F");

            entity.HasOne(d => d.Branch).WithMany(p => p.StockAdjustments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__StockAdju__Branc__6319B466");
        });

        modelBuilder.Entity<StockAdjustmentItem>(entity =>
        {
            entity.HasKey(e => e.StockAdjustmentItemId).HasName("PK__StockAdj__DF39A99D965617A4");

            entity.HasOne(d => d.Item).WithMany(p => p.StockAdjustmentItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__StockAdju__ItemI__68D28DBC");

            entity.HasOne(d => d.ItemVariant).WithMany(p => p.StockAdjustmentItems).HasConstraintName("FK__StockAdju__ItemV__69C6B1F5");

            entity.HasOne(d => d.StockAdjustment).WithMany(p => p.StockAdjustmentItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__StockAdju__Stock__67DE6983");
        });

        modelBuilder.Entity<StockLedger>(entity =>
        {
            entity.HasKey(e => e.StockLedgerId).HasName("PK__StockLed__3E88172BD41F837A");

            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(sysdatetime())");

            entity.HasOne(d => d.Branch).WithMany(p => p.StockLedgers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__StockLedg__Branc__59904A2C");

            entity.HasOne(d => d.Item).WithMany(p => p.StockLedgers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__StockLedg__ItemI__5A846E65");

            entity.HasOne(d => d.ItemVariant).WithMany(p => p.StockLedgers).HasConstraintName("FK__StockLedg__ItemV__5B78929E");
        });

        modelBuilder.Entity<StockTransfer>(entity =>
        {
            entity.HasKey(e => e.StockTransferId).HasName("PK__StockTra__BF0F7F32CA65F931");

            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(sysdatetime())");

            entity.HasOne(d => d.ApprovedByNavigation).WithMany(p => p.StockTransfers).HasConstraintName("FK__StockTran__Appro__7073AF84");

            entity.HasOne(d => d.FromBranch).WithMany(p => p.StockTransferFromBranches)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__StockTran__FromB__6E8B6712");

            entity.HasOne(d => d.ToBranch).WithMany(p => p.StockTransferToBranches)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__StockTran__ToBra__6F7F8B4B");
        });

        modelBuilder.Entity<StockTransferItem>(entity =>
        {
            entity.HasKey(e => e.StockTransferItemId).HasName("PK__StockTra__99BA6C1EBB91B676");

            entity.HasOne(d => d.Item).WithMany(p => p.StockTransferItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__StockTran__ItemI__753864A1");

            entity.HasOne(d => d.ItemVariant).WithMany(p => p.StockTransferItems).HasConstraintName("FK__StockTran__ItemV__762C88DA");

            entity.HasOne(d => d.StockTransfer).WithMany(p => p.StockTransferItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__StockTran__Stock__74444068");
        });

        modelBuilder.Entity<SubCategory>(entity =>
        {
            entity.HasKey(e => e.SubCategoryId).HasName("PK__SubCateg__26BE5B199B0D61FF");

            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.UpdatedOn).HasDefaultValueSql("(sysdatetime())");

            entity.HasOne(d => d.Category).WithMany(p => p.SubCategories).HasConstraintName("FK__SubCatego__Categ__440B1D61");
        });

        modelBuilder.Entity<Supplier>(entity =>
        {
            entity.HasKey(e => e.SupplierId).HasName("PK__Supplier__4BE666B455827D87");

            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.UpdatedOn).HasDefaultValueSql("(sysdatetime())");

            entity.HasOne(d => d.Category).WithMany(p => p.Suppliers).HasConstraintName("FK_Suppliers_Category");
        });

        modelBuilder.Entity<SupplierAccount>(entity =>
        {
            entity.HasOne(d => d.Supplier).WithMany(p => p.SupplierAccounts).HasConstraintName("FK_SupplierAccounts_Suppliers");
        });

        modelBuilder.Entity<SupplierLedger>(entity =>
        {
            entity.HasKey(e => e.SupplierLedgerId).HasName("PK__Supplier__B2A40BFA31A2782B");

            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(sysdatetime())");

            entity.HasOne(d => d.Supplier).WithMany(p => p.SupplierLedgers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__SupplierL__Suppl__6F4A8121");
        });

        modelBuilder.Entity<TaxMaster>(entity =>
        {
            entity.HasKey(e => e.TaxId).HasName("PK__TaxMaste__711BE0ACF88686F7");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
        });

        modelBuilder.Entity<Unit>(entity =>
        {
            entity.HasKey(e => e.UnitId).HasName("PK__Units__44F5ECB5FE7163A7");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CC4CAB1E255D");

            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.UpdatedOn).HasDefaultValueSql("(sysdatetime())");

            entity.HasOne(d => d.Branch).WithMany(p => p.Users).HasConstraintName("FK__Users__BranchId__1F98B2C1");

            entity.HasOne(d => d.Role).WithMany(p => p.Users).HasConstraintName("FK__Users__RoleId__208CD6FA");
        });

        modelBuilder.Entity<UserSession>(entity =>
        {
            entity.HasKey(e => e.SessionId).HasName("PK__UserSess__C9F492903DAC84F4");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.LoginAt).HasDefaultValueSql("(sysdatetime())");

            entity.HasOne(d => d.Device).WithMany(p => p.UserSessions).HasConstraintName("FK__UserSessi__Devic__00DF2177");

            entity.HasOne(d => d.User).WithMany(p => p.UserSessions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserSessi__UserI__7FEAFD3E");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}