<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Cryptography.KeyDerivation" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartWorkerAutomation.Common\SmartWorkerAutomation.Common.csproj" />
    <ProjectReference Include="..\SmartWorkerAutomation.Core\SmartWorkerAutomation.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="MasterTransformation\" />
    <Folder Include="OrganizationTransformation\" />
  </ItemGroup>

</Project>
