<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<None Remove="libwkhtmltox.dll" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="libwkhtmltox.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
				<PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.20.0" />
		<PackageReference Include="ClosedXML" Version="0.104.2" />
		<PackageReference Include="DinkToPdf" Version="1.0.8" />
		<PackageReference Include="Microsoft.AspNetCore.Cryptography.KeyDerivation" Version="10.0.2" />
		<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.9" />
		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
		<PackageReference Include="Serilog" Version="4.3.0" />
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
		<PackageReference Include="ZXing.Net" Version="0.16.11" />
		<PackageReference Include="ZXing.Net.Bindings.SkiaSharp" Version="0.16.22" />
		<PackageReference Include="System.IO.FileSystem" Version="4.3.0" />
		<PackageReference Include="System.Text.Encoding.Extensions" Version="4.3.0" />
		<PackageReference Include="System.Net.Primitives" Version="4.3.0" />
		<PackageReference Include="Microsoft.Win32.Primitives" Version="4.3.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SmartWorkerAutomation.Common\SmartWorkerAutomation.Common.csproj" />
		<ProjectReference Include="..\SmartWorkerAutomation.Core\SmartWorkerAutomation.Core.csproj" />
		<ProjectReference Include="..\SmartWorkerAutomation.Transformation\SmartWorkerAutomation.Transformation.csproj" />
	</ItemGroup>

</Project>
